import type { Achievement, AchievementType, Player, Region, Role } from "./types";
import generatedAchievements from "./players.generated.json";

export const DATA_NOTE =
  "Illustrative dataset for this prototype — honors are approximate and seeded by hand, not yet synced from Leaguepedia.";

const rep = (type: AchievementType, years: number[], team?: string): Achievement[] =>
  years.map((year) => ({ type, year, team }));

const mvp = (type: AchievementType, year: number, share: number, team?: string): Achievement => ({
  type,
  year,
  share,
  team,
});

const CURATED_PLAYERS: Player[] = [
  // ───────────────────────── LCK ─────────────────────────
  {
    id: "faker",
    name: "Faker",
    realName: "Lee Sang-hyeok",
    region: "LCK",
    role: "Mid",
    team: "T1",
    country: "🇰🇷",
    active: true,
    debutYear: 2013,
    blurb: "The Unkillable Demon King. The defining career of the sport.",
    achievements: [
      ...rep("worlds_title", [2013, 2015, 2016, 2023, 2024, 2025], "T1"),
      ...rep("msi_title", [2016, 2017], "T1"),
      ...rep("ewc_title", [2024], "T1"),
      ...rep("asian_games_gold", [2022], "South Korea"),
      ...rep("regional_title", [2013, 2015, 2016, 2019, 2022, 2023, 2024, 2025, 2015, 2016], "T1"),
      mvp("worlds_mvp", 2016, 1.0, "T1"),
      mvp("msi_mvp", 2017, 0.9, "T1"),
      mvp("season_mvp", 2015, 0.82, "T1"),
      mvp("season_mvp", 2019, 0.7, "T1"),
      ...rep("all_pro_1", [2015, 2016, 2017, 2019, 2021, 2023, 2024], "T1"),
      ...rep("all_pro_2", [2018, 2022], "T1"),
      ...rep("worlds_runnerup", [2017, 2022], "T1"),
    ],
  },
  {
    id: "showmaker",
    name: "ShowMaker",
    realName: "Heo Su",
    region: "LCK",
    role: "Mid",
    team: "Dplus KIA",
    country: "🇰🇷",
    active: true,
    debutYear: 2019,
    blurb: "Coronated at 2020 Worlds; the cleanest solo-queue mechanics of his era.",
    achievements: [
      ...rep("worlds_title", [2020], "DAMWON"),
      ...rep("regional_title", [2020, 2021], "DAMWON"),
      ...rep("worlds_runnerup", [2021], "DK"),
      mvp("season_mvp", 2020, 0.8, "DAMWON"),
      ...rep("all_pro_1", [2020, 2021, 2022], "DK"),
      ...rep("all_pro_2", [2023], "Dplus KIA"),
    ],
  },
  {
    id: "chovy",
    name: "Chovy",
    realName: "Jeong Ji-hoon",
    region: "LCK",
    role: "Mid",
    team: "Gen.G",
    country: "🇰🇷",
    active: true,
    debutYear: 2018,
    blurb: "Statistically dominant laner; the great 'uncrowned at Worlds' question.",
    achievements: [
      ...rep("msi_title", [2024, 2025], "Gen.G"),
      ...rep("regional_title", [2022, 2023, 2024, 2025, 2024, 2026], "Gen.G"),
      mvp("season_mvp", 2023, 0.78, "Gen.G"),
      mvp("season_mvp", 2024, 0.85, "Gen.G"),
      mvp("msi_mvp", 2024, 0.55, "Gen.G"),
      mvp("msi_mvp", 2025, 1.0, "Gen.G"),
      ...rep("ewc_title", [2025], "Gen.G"),
      ...rep("asian_games_gold", [2022], "South Korea"),
      ...rep("all_pro_1", [2020, 2021, 2022, 2023, 2024, 2025], "Gen.G"),
    ],
  },
  {
    id: "zeus",
    name: "Zeus",
    realName: "Choi Woo-je",
    region: "LCK",
    role: "Top",
    team: "HLE",
    country: "🇰🇷",
    active: true,
    debutYear: 2022,
    blurb: "Two-time world champion top laner with carry-threat teleports.",
    achievements: [
      ...rep("worlds_title", [2023, 2024], "T1"),
      ...rep("ewc_title", [2024], "T1"),
      ...rep("asian_games_gold", [2022], "South Korea"),
      ...rep("regional_title", [2024, 2025], "T1"),
      ...rep("all_pro_1", [2023, 2024], "T1"),
      ...rep("all_pro_2", [2025], "HLE"),
      ...rep("first_stand_title", [2025], "Hanwha Life"),
    ],
  },
  {
    id: "oner",
    name: "Oner",
    realName: "Mun Hyeon-jun",
    region: "LCK",
    role: "Jungle",
    team: "T1",
    country: "🇰🇷",
    active: true,
    debutYear: 2021,
    achievements: [
      ...rep("worlds_title", [2023, 2024, 2025], "T1"),
      ...rep("ewc_title", [2024], "T1"),
      ...rep("regional_title", [2024, 2025], "T1"),
      ...rep("all_pro_1", [2023], "T1"),
      ...rep("all_pro_2", [2024], "T1"),
      ...rep("worlds_runnerup", [2022], "T1"),
    ],
  },
  {
    id: "gumayusi",
    name: "Gumayusi",
    realName: "Lee Min-hyeong",
    region: "LCK",
    role: "Bot",
    team: "Hanwha Life",
    country: "🇰🇷",
    active: true,
    debutYear: 2021,
    achievements: [
      ...rep("worlds_title", [2023, 2024, 2025], "T1"),
      ...rep("ewc_title", [2024], "T1"),
      mvp("worlds_mvp", 2025, 1.0, "T1"),
      ...rep("regional_title", [2024, 2025], "T1"),
      ...rep("all_pro_1", [2024], "T1"),
      ...rep("all_pro_2", [2023], "T1"),
      ...rep("worlds_runnerup", [2022], "T1"),
    ],
  },
  {
    id: "keria",
    name: "Keria",
    realName: "Ryu Min-seok",
    region: "LCK",
    role: "Support",
    team: "T1",
    country: "🇰🇷",
    active: true,
    debutYear: 2020,
    blurb: "Generational support — defines the role's modern playmaking ceiling.",
    achievements: [
      ...rep("worlds_title", [2023, 2024, 2025], "T1"),
      ...rep("regional_title", [2024, 2025], "T1"),
      ...rep("all_pro_1", [2021, 2023, 2024, 2025], "T1"),
      ...rep("ewc_title", [2024], "T1"),
      ...rep("asian_games_gold", [2022], "South Korea"),
      ...rep("worlds_runnerup", [2022], "T1"),
    ],
  },
  {
    id: "beryl",
    name: "BeryL",
    realName: "Cho Geon-hee",
    region: "LCK",
    role: "Support",
    team: "Dplus KIA",
    country: "🇰🇷",
    active: true,
    debutYear: 2017,
    blurb: "Won Worlds with two different teams — the ultimate roster value pick.",
    achievements: [
      ...rep("worlds_title", [2020, 2022], "DAMWON / DRX"),
      ...rep("regional_title", [2020], "DAMWON"),
      ...rep("worlds_runnerup", [2021], "DK"),
      ...rep("all_pro_1", [2020], "DAMWON"),
      ...rep("all_pro_2", [2022], "DRX"),
    ],
  },
  {
    id: "deft",
    name: "Deft",
    realName: "Kim Hyuk-kyu",
    region: "LCK",
    role: "Bot",
    team: "KT Rolster",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    blurb: "A decade of waiting, rewarded with the 2022 Worlds title.",
    achievements: [
      ...rep("worlds_title", [2022], "DRX"),
      ...rep("msi_title", [2015], "EDward Gaming"),
      ...rep("regional_title", [2015], "KT"),
      ...rep("all_pro_1", [2014, 2022], "KT / DRX"),
      ...rep("all_pro_2", [2015, 2021], "KT"),
    ],
  },
  {
    id: "canyon",
    name: "Canyon",
    realName: "Kim Geon-bu",
    region: "LCK",
    role: "Jungle",
    team: "Gen.G",
    country: "🇰🇷",
    active: true,
    debutYear: 2018,
    blurb: "Worlds champion jungler; widely rated the most complete of his generation.",
    achievements: [
      ...rep("worlds_title", [2020], "DAMWON"),
      ...rep("msi_title", [2024, 2025], "Gen.G"),
      ...rep("regional_title", [2020, 2021, 2024, 2025, 2026], "DAMWON / Gen.G"),
      ...rep("worlds_runnerup", [2021], "DK"),
      mvp("season_mvp", 2021, 0.8, "DK"),
      mvp("msi_mvp", 2024, 0.6, "Gen.G"),
      ...rep("ewc_title", [2025], "Gen.G"),
      ...rep("all_pro_1", [2020, 2021, 2024], "DK / Gen.G"),
    ],
  },
  {
    id: "ruler",
    name: "Ruler",
    realName: "Park Jae-hyuk",
    region: "LCK",
    role: "Bot",
    team: "Gen.G",
    country: "🇰🇷",
    active: true,
    debutYear: 2016,
    blurb: "2017 Worlds Finals MVP; later an LPL champion. Cross-region résumé.",
    achievements: [
      ...rep("worlds_title", [2017], "Samsung"),
      ...rep("msi_title", [2023], "JD Gaming"),
      ...rep("msi_title", [2025], "Gen.G"),
      ...rep("regional_title", [2022, 2023, 2023, 2025, 2026], "JDG / Gen.G"),
      mvp("worlds_mvp", 2017, 1.0, "Samsung"),
      ...rep("ewc_title", [2025], "Gen.G"),
      ...rep("asian_games_gold", [2022], "South Korea"),
      mvp("season_mvp", 2025, 0.8, "Gen.G"),
      mvp("season_mvp", 2023, 0.6, "JDG"),
      ...rep("all_pro_1", [2017, 2022, 2023, 2024], "Samsung / JDG / Gen.G"),
      ...rep("worlds_runnerup", [2016], "Samsung"),
    ],
  },

  // ───────────────────────── LPL ─────────────────────────
  {
    id: "uzi",
    name: "Uzi",
    realName: "Jian Zi-Hao",
    region: "LPL",
    role: "Bot",
    team: "EDward Gaming",
    country: "🇨🇳",
    active: false,
    debutYear: 2012,
    blurb: "The prodigy who carried a generation — MSI champion, never a Worlds title.",
    achievements: [
      ...rep("msi_title", [2018], "RNG"),
      ...rep("regional_title", [2016, 2018], "RNG"),
      mvp("msi_mvp", 2018, 1.0, "RNG"),
      mvp("season_mvp", 2018, 0.8, "RNG"),
      ...rep("all_pro_1", [2016, 2017, 2018, 2019], "RNG"),
      ...rep("worlds_runnerup", [2013, 2014], "Royal Club / Star Horn Royal Club"),
    ],
  },
  {
    id: "jackeylove",
    name: "JackeyLove",
    realName: "Yu Wen-Bo",
    region: "LPL",
    role: "Bot",
    team: "TES",
    country: "🇨🇳",
    active: true,
    debutYear: 2017,
    achievements: [
      ...rep("worlds_title", [2018], "Invictus Gaming"),
      ...rep("regional_title", [2019, 2020, 2024, 2025], "IG / TES"),
      ...rep("msc_title", [2020], "Top Esports"),
      ...rep("all_pro_1", [2020, 2021, 2024], "TES"),
      mvp("season_mvp", 2021, 0.5, "TES"),
    ],
  },
  {
    id: "theshy",
    name: "TheShy",
    realName: "Kang Seung-lok",
    region: "LPL",
    role: "Top",
    team: "Invictus Gaming",
    country: "🇰🇷",
    active: true,
    debutYear: 2017,
    blurb: "2018 world champion known for the most aggressive top-lane ever.",
    achievements: [
      ...rep("worlds_title", [2018], "Invictus Gaming"),
      ...rep("regional_title", [2019], "IG"),
      ...rep("worlds_runnerup", [2023], "Weibo Gaming"),
      ...rep("all_pro_1", [2018, 2019, 2021], "IG"),
      ...rep("all_pro_2", [2024], "Weibo Gaming"),
    ],
  },
  {
    id: "rookie",
    name: "Rookie",
    realName: "Song Eui-jin",
    region: "LPL",
    role: "Mid",
    team: "Invictus Gaming",
    country: "🇰🇷",
    active: true,
    debutYear: 2014,
    achievements: [
      ...rep("worlds_title", [2018], "Invictus Gaming"),
      ...rep("regional_title", [2018, 2019], "IG"),
      mvp("season_mvp", 2017, 0.72, "IG"),
      mvp("season_mvp", 2018, 0.62, "IG"),
      ...rep("all_pro_1", [2017, 2018, 2019], "IG"),
    ],
  },
  {
    id: "knight",
    name: "knight",
    realName: "Zhuo Ding",
    region: "LPL",
    role: "Mid",
    team: "Bilibili Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2017,
    blurb: "The LPL's highest-ceiling mid — chasing the Worlds title with Bilibili Gaming.",
    achievements: [
      ...rep("msi_title", [2023], "JD Gaming"),
      ...rep("msc_title", [2020], "Top Esports"),
      ...rep("regional_title", [2023, 2023], "JD Gaming"),
      ...rep("regional_title", [2024, 2025, 2026], "Bilibili Gaming"),
      ...rep("worlds_runnerup", [2024], "Bilibili Gaming"),
      ...rep("first_stand_title", [2026], "Bilibili Gaming"),
      mvp("season_mvp", 2021, 0.8, "TES"),
      mvp("season_mvp", 2024, 0.85, "Bilibili Gaming"),
      mvp("finals_mvp", 2024, 0.9, "Bilibili Gaming"),
      ...rep("all_pro_1", [2021, 2024, 2025], "TES / BLG"),
    ],
  },
  {
    id: "xiaohu",
    name: "Xiaohu",
    realName: "Li Yuan-Hao",
    region: "LPL",
    role: "Mid",
    team: "Weibo Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2015,
    blurb: "Two-time MSI champion at the heart of the RNG dynasty.",
    achievements: [
      ...rep("msi_title", [2018, 2021, 2022], "RNG"),
      ...rep("regional_title", [2016, 2018, 2021, 2022], "RNG"),
      ...rep("worlds_runnerup", [2023], "Weibo Gaming"),
      ...rep("all_pro_1", [2017, 2020, 2021], "RNG"),
    ],
  },
  {
    id: "ming",
    name: "Ming",
    realName: "Shi Sen-Ming",
    region: "LPL",
    role: "Support",
    team: "RNG",
    country: "🇨🇳",
    active: true,
    debutYear: 2016,
    achievements: [
      ...rep("msi_title", [2018, 2021, 2022], "RNG"),
      ...rep("regional_title", [2018, 2021], "RNG"),
      ...rep("all_pro_1", [2018, 2021, 2022], "RNG"),
    ],
  },
  {
    id: "scout",
    name: "Scout",
    realName: "Lee Ye-chan",
    region: "LCK",
    role: "Mid",
    team: "Nongshim RedForce",
    country: "🇰🇷",
    active: true,
    debutYear: 2015,
    achievements: [
      ...rep("worlds_title", [2021], "EDward Gaming"),
      ...rep("regional_title", [2020, 2021], "EDG"),
      mvp("season_mvp", 2020, 0.6, "EDG"),
      ...rep("all_pro_1", [2020, 2021], "EDG"),
    ],
  },
  {
    id: "jiejie",
    name: "JieJie",
    realName: "Zhao Li-Jie",
    region: "LPL",
    role: "Jungle",
    team: "Weibo Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2019,
    achievements: [
      ...rep("worlds_title", [2021], "EDward Gaming"),
      ...rep("regional_title", [2021, 2024], "EDG / TES"),
      ...rep("all_pro_1", [2021, 2022], "EDG"),
    ],
  },
  {
    id: "doinb",
    name: "Doinb",
    realName: "Kim Tae-sang",
    region: "LPL",
    role: "Mid",
    team: "Ninjas in Pyjamas",
    country: "🇰🇷",
    active: true,
    debutYear: 2016,
    achievements: [
      ...rep("worlds_title", [2019], "FunPlus Phoenix"),
      ...rep("regional_title", [2019], "FPX"),
      mvp("season_mvp", 2019, 1.0, "FPX"),
      ...rep("all_pro_1", [2019, 2020], "FPX"),
    ],
  },
  {
    id: "tian",
    name: "Tian",
    realName: "Gao Tian-Liang",
    region: "LPL",
    role: "Jungle",
    team: "FunPlus Phoenix",
    country: "🇨🇳",
    active: true,
    debutYear: 2017,
    achievements: [
      ...rep("worlds_title", [2019], "FunPlus Phoenix"),
      ...rep("regional_title", [2019], "FPX"),
      mvp("worlds_mvp", 2019, 1.0, "FPX"),
      ...rep("all_pro_1", [2019], "FPX"),
    ],
  },
  {
    id: "bin",
    name: "Bin",
    realName: "Chen Ze-Bin",
    region: "LPL",
    role: "Top",
    team: "Bilibili Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2019,
    blurb: "Carry top laner of the modern LPL; agonizingly close at 2024 Worlds.",
    achievements: [
      ...rep("msi_title", [2022], "RNG"),
      ...rep("regional_title", [2024, 2025, 2026], "BLG"),
      ...rep("worlds_runnerup", [2020, 2024], "Suning / Bilibili Gaming"),
      mvp("season_mvp", 2024, 0.7, "BLG"),
      ...rep("first_stand_title", [2026], "Bilibili Gaming"),
      ...rep("all_pro_1", [2024, 2025], "BLG"),
    ],
  },

  // ───────────────────────── LEC ─────────────────────────
  {
    id: "caps",
    name: "Caps",
    realName: "Rasmus Winther",
    region: "LEC",
    role: "Mid",
    team: "G2 Esports",
    country: "🇩🇰",
    active: true,
    debutYear: 2016,
    blurb: "The West's best — an MSI title and two Worlds finals appearances.",
    achievements: [
      ...rep("msi_title", [2019], "G2 Esports"),
      ...rep("regional_title", [2018, 2019, 2020, 2022, 2023, 2024, 2025, 2019, 2026], "Fnatic / G2"),
      ...rep("worlds_runnerup", [2018, 2019], "Fnatic / G2"),
      mvp("season_mvp", 2018, 0.7, "Fnatic"),
      mvp("season_mvp", 2022, 0.66, "G2"),
      ...rep("all_pro_1", [2018, 2019, 2020, 2022, 2023], "Fnatic / G2"),
    ],
  },
  {
    id: "jankos",
    name: "Jankos",
    realName: "Marcin Jankowski",
    region: "LEC",
    role: "Jungle",
    team: "GIANTX",
    country: "🇵🇱",
    active: false,
    debutYear: 2013,
    achievements: [
      ...rep("msi_title", [2019], "G2 Esports"),
      ...rep("regional_title", [2019, 2020, 2021], "G2"),
      ...rep("worlds_runnerup", [2019], "G2 Esports"),
      ...rep("all_pro_1", [2019, 2020], "G2"),
    ],
  },
  {
    id: "rekkles",
    name: "Rekkles",
    realName: "Martin Larsson",
    region: "LEC",
    role: "Bot",
    team: "Fnatic",
    country: "🇸🇪",
    active: true,
    debutYear: 2013,
    blurb: "The face of European bot lane for a decade.",
    achievements: [
      ...rep("regional_title", [2015, 2017, 2018, 2020, 2021], "Fnatic / G2"),
      ...rep("worlds_runnerup", [2018], "Fnatic"),
      ...rep("all_pro_1", [2017, 2018, 2019, 2020], "Fnatic"),
    ],
  },
  {
    id: "mikyx",
    name: "Mikyx",
    realName: "Mihael Mehle",
    region: "LEC",
    role: "Support",
    team: "SK Gaming",
    country: "🇸🇮",
    active: true,
    debutYear: 2016,
    achievements: [
      ...rep("msi_title", [2019], "G2 Esports"),
      ...rep("regional_title", [2019, 2020, 2024], "G2"),
      ...rep("worlds_runnerup", [2019], "G2 Esports"),
      ...rep("all_pro_1", [2019], "G2"),
    ],
  },

  // ───────────────────────── LCS ─────────────────────────
  {
    id: "bjergsen",
    name: "Bjergsen",
    realName: "Søren Bjerg",
    region: "LCS",
    role: "Mid",
    team: "Team Liquid",
    country: "🇩🇰",
    active: false,
    debutYear: 2013,
    blurb: "North America's defining mid laner and serial domestic MVP.",
    achievements: [
      ...rep("regional_title", [2014, 2015, 2016, 2017, 2020], "TSM"),
      mvp("season_mvp", 2014, 0.9, "TSM"),
      mvp("season_mvp", 2016, 0.8, "TSM"),
      mvp("season_mvp", 2018, 0.78, "TSM"),
      mvp("season_mvp", 2020, 0.7, "TSM"),
      ...rep("all_pro_1", [2014, 2015, 2016, 2017, 2018, 2020], "TSM"),
    ],
  },
  {
    id: "doublelift",
    name: "Doublelift",
    realName: "Yiliang Peng",
    region: "LCS",
    role: "Bot",
    team: "100 Thieves",
    country: "🇺🇸",
    active: false,
    debutYear: 2011,
    blurb: "Eight-time domestic champion and the loudest carry NA ever produced.",
    achievements: [
      ...rep("regional_title", [2015, 2016, 2017, 2018, 2019, 2020], "CLG / TSM / TL"),
      mvp("season_mvp", 2018, 0.6, "TL"),
      ...rep("all_pro_1", [2015, 2016, 2018, 2019], "TSM / TL"),
    ],
  },
  {
    id: "corejj",
    name: "CoreJJ",
    realName: "Jo Yong-in",
    region: "LCS",
    role: "Support",
    team: "Team Liquid",
    country: "🇰🇷",
    active: true,
    debutYear: 2014,
    blurb: "A Worlds champion support who became NA's gold standard at the role.",
    achievements: [
      ...rep("worlds_title", [2017], "Samsung"),
      ...rep("worlds_runnerup", [2016], "Samsung Galaxy"),
      ...rep("regional_title", [2019, 2020, 2025], "Team Liquid"),
      mvp("finals_mvp", 2019, 0.9, "Team Liquid"),
      ...rep("all_pro_1", [2019, 2020, 2021, 2025], "Team Liquid"),
    ],
  },
  {
    id: "blaber",
    name: "Blaber",
    realName: "Robert Huang",
    region: "LCS",
    role: "Jungle",
    team: "Cloud9",
    country: "🇺🇸",
    active: true,
    debutYear: 2018,
    achievements: [
      ...rep("regional_title", [2020, 2021, 2025], "Cloud9"),
      mvp("season_mvp", 2021, 0.82, "Cloud9"),
      mvp("season_mvp", 2022, 0.6, "Cloud9"),
      ...rep("all_pro_1", [2021, 2022, 2025], "Cloud9"),
    ],
  },
  {
    id: "impact",
    name: "Impact",
    realName: "Jung Eon-yeong",
    region: "LCS",
    role: "Top",
    team: "Sentinels",
    country: "🇰🇷",
    active: true,
    debutYear: 2013,
    blurb: "A 2013 world champion who became one of NA's most durable veterans.",
    achievements: [
      ...rep("worlds_title", [2013], "SKT T1"),
      ...rep("regional_title", [2013, 2025], "SKT / FlyQuest"),
      ...rep("all_pro_1", [2018], "Cloud9"),
      ...rep("all_pro_2", [2020, 2025], "EG / FlyQuest"),
    ],
  },

  // ───────────────── additions: legends & stars ─────────────────
  {
    id: "mata",
    name: "Mata",
    realName: "Cho Se-hyeong",
    region: "LCK",
    role: "Support",
    team: "Royal Never Give Up",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    blurb: "First support to win Worlds Finals MVP — the cerebral standard for the role.",
    achievements: [
      ...rep("worlds_title", [2014], "Samsung White"),
      mvp("worlds_mvp", 2014, 1.0, "Samsung White"),
      ...rep("all_pro_1", [2014, 2017], "Samsung / RNG"),
    ],
  },
  {
    id: "madlife",
    name: "MadLife",
    realName: "Hong Min-gi",
    region: "LCK",
    role: "Support",
    team: "CJ Entus",
    country: "🇰🇷",
    active: false,
    debutYear: 2012,
    blurb: "The support who redefined the role — revered, if title-light.",
    achievements: [
      ...rep("worlds_runnerup", [2012], "Azubu Frost"),
      ...rep("regional_title", [2012], "Azubu Frost"),
      ...rep("all_pro_1", [2012], "Azubu Frost"),
      ...rep("all_pro_2", [2013], "CJ Entus"),
    ],
  },
  {
    id: "bengi",
    name: "Bengi",
    realName: "Bae Seong-ung",
    region: "LCK",
    role: "Jungle",
    team: "SKT T1",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    blurb: "Faker's jungler through three world titles.",
    achievements: [
      ...rep("worlds_title", [2013, 2015, 2016], "SKT T1"),
      ...rep("msi_title", [2016], "SKT T1"),
      ...rep("regional_title", [2013, 2015, 2016], "SKT T1"),
      ...rep("worlds_runnerup", [2017], "SKT T1"),
      ...rep("all_pro_1", [2013], "SKT T1"),
      ...rep("all_pro_2", [2015], "SKT T1"),
    ],
  },
  {
    id: "marin",
    name: "MaRin",
    realName: "Jang Gyeong-hwan",
    region: "LCK",
    role: "Top",
    team: "Top Esports",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    blurb: "2015 Worlds Finals MVP at the peak of SKT's reign.",
    achievements: [
      ...rep("worlds_title", [2015], "SKT T1"),
      mvp("worlds_mvp", 2015, 1.0, "SKT T1"),
      ...rep("regional_title", [2015], "SKT T1"),
      ...rep("all_pro_1", [2015], "SKT T1"),
    ],
  },
  {
    id: "bang",
    name: "Bang",
    realName: "Bae Jun-sik",
    region: "LCK",
    role: "Bot",
    team: "SKT T1",
    country: "🇰🇷",
    active: false,
    debutYear: 2014,
    achievements: [
      ...rep("worlds_title", [2015, 2016], "SKT T1"),
      ...rep("msi_title", [2016, 2017], "SKT T1"),
      ...rep("regional_title", [2015, 2016, 2017], "SKT T1"),
      ...rep("worlds_runnerup", [2017], "SKT T1"),
      ...rep("all_pro_1", [2016], "SKT T1"),
      ...rep("all_pro_2", [2015], "SKT T1"),
    ],
  },
  {
    id: "wolf",
    name: "Wolf",
    realName: "Lee Jae-wan",
    region: "LCK",
    role: "Support",
    team: "SuperMassive",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    achievements: [
      ...rep("worlds_title", [2015, 2016], "SKT T1"),
      ...rep("msi_title", [2016, 2017], "SKT T1"),
      ...rep("regional_title", [2015, 2016, 2017], "SKT T1"),
      ...rep("worlds_runnerup", [2017], "SKT T1"),
      ...rep("all_pro_1", [2016], "SKT T1"),
    ],
  },
  {
    id: "peanut",
    name: "Peanut",
    realName: "Han Wang-ho",
    region: "LCK",
    role: "Jungle",
    team: "Hanwha Life",
    country: "🇰🇷",
    active: false,
    debutYear: 2015,
    achievements: [
      ...rep("msi_title", [2017], "SKT T1"),
      ...rep("worlds_runnerup", [2017], "SKT T1"),
      ...rep("regional_title", [2017, 2022, 2023, 2024], "SKT / Gen.G"),
      ...rep("first_stand_title", [2025], "Hanwha Life"),
      ...rep("all_pro_1", [2022], "Gen.G"),
      ...rep("all_pro_2", [2017], "SKT T1"),
    ],
  },
  {
    id: "khan",
    name: "Khan",
    realName: "Kim Dong-ha",
    region: "LCK",
    role: "Top",
    team: "DWG KIA",
    country: "🇰🇷",
    active: false,
    debutYear: 2015,
    achievements: [
      mvp("season_mvp", 2018, 0.7, "Kingzone"),
      ...rep("regional_title", [2018, 2019, 2021], "Kingzone / SKT / DWG KIA"),
      ...rep("worlds_runnerup", [2021], "DWG KIA"),
      ...rep("all_pro_1", [2018, 2019], "Kingzone / SKT"),
    ],
  },
  {
    id: "nuguri",
    name: "Nuguri",
    realName: "Jang Ha-gwon",
    region: "LCK",
    role: "Top",
    team: "Dplus KIA",
    country: "🇰🇷",
    active: false,
    debutYear: 2018,
    achievements: [
      ...rep("worlds_title", [2020], "DAMWON"),
      ...rep("regional_title", [2020], "DAMWON"),
      ...rep("worlds_runnerup", [2021], "FunPlus Phoenix"),
      ...rep("all_pro_1", [2020], "DAMWON"),
    ],
  },
  {
    id: "viper",
    name: "Viper",
    realName: "Park Do-hyeon",
    region: "LCK",
    role: "Bot",
    team: "Bilibili Gaming",
    country: "🇰🇷",
    active: true,
    debutYear: 2020,
    achievements: [
      ...rep("worlds_title", [2021], "EDward Gaming"),
      ...rep("regional_title", [2025], "Hanwha Life"),
      ...rep("regional_title", [2026], "Bilibili Gaming"),
      ...rep("all_pro_1", [2023, 2024], "EDG / Hanwha Life"),
      ...rep("first_stand_title", [2025, 2026], "Hanwha Life / BLG"),
    ],
  },
  {
    id: "karsa",
    name: "Karsa",
    realName: "Hung Hao-Hsuan",
    region: "LPL",
    role: "Jungle",
    team: "PSG Talon",
    country: "🇹🇼",
    active: false,
    debutYear: 2015,
    achievements: [
      ...rep("msi_title", [2018], "RNG"),
      ...rep("msc_title", [2020], "Top Esports"),
      ...rep("regional_title", [2018, 2021], "RNG / TES"),
      ...rep("all_pro_1", [2018, 2020], "RNG / TES"),
    ],
  },
  {
    id: "ning",
    name: "Ning",
    realName: "Gao Zhen-Ning",
    region: "LPL",
    role: "Jungle",
    team: "Ultra Prime",
    country: "🇨🇳",
    active: false,
    debutYear: 2017,
    blurb: "First jungler to win Worlds Finals MVP (2018).",
    achievements: [
      ...rep("worlds_title", [2018], "Invictus Gaming"),
      mvp("worlds_mvp", 2018, 1.0, "Invictus Gaming"),
      ...rep("regional_title", [2019], "IG"),
      ...rep("all_pro_1", [2018], "Invictus Gaming"),
    ],
  },
  {
    id: "crisp",
    name: "Crisp",
    realName: "Liu Qing-Song",
    region: "LPL",
    role: "Support",
    team: "Weibo Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2018,
    achievements: [
      ...rep("worlds_title", [2019], "FunPlus Phoenix"),
      ...rep("regional_title", [2019], "FPX"),
      ...rep("worlds_runnerup", [2023], "Weibo Gaming"),
      ...rep("all_pro_1", [2019], "FPX"),
      ...rep("all_pro_2", [2020], "FPX"),
    ],
  },
  {
    id: "wei",
    name: "Wei",
    realName: "Yan Yang-Wei",
    region: "LPL",
    role: "Jungle",
    team: "Invictus Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2020,
    blurb: "Engine of modern BLG — agonizingly close at 2024 Worlds.",
    achievements: [
      ...rep("msi_title", [2021, 2022], "RNG"),
      ...rep("regional_title", [2024, 2025], "BLG"),
      ...rep("worlds_runnerup", [2024], "Bilibili Gaming"),
      mvp("season_mvp", 2024, 0.6, "BLG"),
      ...rep("all_pro_1", [2024, 2025], "BLG"),
    ],
  },
  {
    id: "perkz",
    name: "Perkz",
    realName: "Luka Perković",
    region: "LEC",
    role: "Mid",
    team: "G2 Esports",
    country: "🇭🇷",
    active: false,
    debutYear: 2015,
    blurb: "Europe's most decorated — an MSI title and two Worlds finals.",
    achievements: [
      ...rep("msi_title", [2019], "G2 Esports"),
      ...rep("worlds_runnerup", [2019], "G2 Esports"),
      ...rep("regional_title", [2017, 2018, 2019, 2019, 2020], "G2 Esports"),
      mvp("season_mvp", 2017, 0.6, "G2 Esports"),
      ...rep("all_pro_1", [2018, 2019], "G2 Esports"),
    ],
  },
  {
    id: "hylissang",
    name: "Hylissang",
    realName: "Zdravets Galabov",
    region: "LEC",
    role: "Support",
    team: "Team Vitality",
    country: "🇧🇬",
    active: false,
    debutYear: 2014,
    achievements: [
      ...rep("regional_title", [2018], "Fnatic"),
      ...rep("worlds_runnerup", [2018], "Fnatic"),
      ...rep("all_pro_1", [2018, 2022], "Fnatic"),
      ...rep("all_pro_2", [2019], "Fnatic"),
    ],
  },
  {
    id: "pray",
    name: "PraY",
    realName: "Kim Jong-in",
    region: "LCK",
    role: "Bot",
    team: "KT Rolster",
    country: "🇰🇷",
    active: false,
    debutYear: 2012,
    blurb: "Half of the iconic PraY–GorillA bot lane.",
    achievements: [
      ...rep("worlds_runnerup", [2015], "KOO Tigers"),
      ...rep("regional_runnerup", [2016], "ROX Tigers"),
      ...rep("all_pro_1", [2015, 2016], "ROX Tigers"),
      ...rep("all_pro_2", [2017], "Longzhu"),
    ],
  },
  {
    id: "gorilla",
    name: "GorillA",
    realName: "Kang Beom-hyeon",
    region: "LCK",
    role: "Support",
    team: "Gen.G",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    achievements: [
      ...rep("worlds_runnerup", [2015], "KOO Tigers"),
      ...rep("all_pro_1", [2015, 2016], "ROX Tigers"),
    ],
  },
  {
    id: "doran",
    name: "Doran",
    realName: "Choi Hyeon-jun",
    region: "LCK",
    role: "Top",
    team: "T1",
    country: "🇰🇷",
    active: true,
    debutYear: 2019,
    blurb: "Replaced Zeus on T1 and won Worlds 2025 — the third straight title.",
    achievements: [
      ...rep("worlds_title", [2025], "T1"),
      ...rep("regional_title", [2023], "Gen.G"),
      ...rep("all_pro_1", [2025], "T1"),
    ],
  },
  {
    id: "kiin",
    name: "Kiin",
    realName: "Kim Gi-in",
    region: "LCK",
    role: "Top",
    team: "Gen.G",
    country: "🇰🇷",
    active: true,
    debutYear: 2017,
    achievements: [
      ...rep("msi_title", [2024, 2025], "Gen.G"),
      ...rep("ewc_title", [2025], "Gen.G"),
      ...rep("regional_title", [2025, 2026], "Gen.G"),
      ...rep("all_pro_1", [2024, 2025], "Gen.G"),
    ],
  },
  {
    id: "zeka",
    name: "Zeka",
    realName: "Kim Geon-woo",
    region: "LCK",
    role: "Mid",
    team: "Hanwha Life",
    country: "🇰🇷",
    active: true,
    debutYear: 2019,
    blurb: "2022 world champion with DRX; First Stand 2025 MVP.",
    achievements: [
      ...rep("worlds_title", [2022], "DRX"),
      ...rep("first_stand_title", [2025], "Hanwha Life"),
      ...rep("regional_title", [2025], "Hanwha Life"),
      ...rep("all_pro_1", [2025], "Hanwha Life"),
    ],
  },

  // ───────────── LPL / LCK: Asian Games & EWC additions ─────────────
  {
    id: "kanavi",
    name: "Kanavi",
    realName: "Seo Jin-hyeok",
    region: "LPL",
    role: "Jungle",
    team: "Hanwha Life",
    country: "🇰🇷",
    active: true,
    debutYear: 2018,
    blurb: "Asian Games gold medalist and MSI champion — JDG's franchise jungler.",
    achievements: [
      ...rep("msi_title", [2023], "JD Gaming"),
      ...rep("asian_games_gold", [2022], "South Korea"),
      ...rep("regional_title", [2022, 2023, 2023], "JDG"),
      ...rep("all_pro_1", [2023], "JDG"),
    ],
  },
  {
    id: "duro",
    name: "Duro",
    region: "LCK",
    role: "Support",
    team: "Gen.G",
    country: "🇰🇷",
    active: true,
    debutYear: 2021,
    blurb: "Gen.G's 2025 support — MSI and EWC champion in his breakout season.",
    achievements: [
      ...rep("msi_title", [2025], "Gen.G"),
      ...rep("ewc_title", [2025], "Gen.G"),
      ...rep("regional_title", [2025, 2026], "Gen.G"),
    ],
  },

  // ───────────────────────── PCS (Taiwan / Pacific) ─────────────────────────
  {
    id: "toyz",
    name: "Toyz",
    realName: "Kurtis Lau Wai-Kin",
    region: "PCS",
    role: "Mid",
    team: "Taipei Assassins",
    country: "🇭🇰",
    active: false,
    debutYear: 2012,
    blurb: "Mid laner of the 2012 world champion Taipei Assassins — the region's lone Worlds title.",
    achievements: [
      ...rep("worlds_title", [2012], "Taipei Assassins"),
      ...rep("regional_title", [2012], "Taipei Assassins"),
    ],
  },
  {
    id: "stanley",
    name: "Stanley",
    realName: "Wang Jun-Tsan",
    region: "PCS",
    role: "Top",
    team: "Taipei Assassins",
    country: "🇹🇼",
    active: false,
    debutYear: 2012,
    achievements: [
      ...rep("worlds_title", [2012], "Taipei Assassins"),
      ...rep("regional_title", [2012], "Taipei Assassins"),
    ],
  },
  {
    id: "lilballz",
    name: "Lilballz",
    realName: "Alex Sung",
    region: "PCS",
    role: "Jungle",
    team: "Taipei Assassins",
    country: "🇹🇼",
    active: false,
    debutYear: 2012,
    achievements: [
      ...rep("worlds_title", [2012], "Taipei Assassins"),
      ...rep("regional_title", [2012], "Taipei Assassins"),
    ],
  },
  {
    id: "bebe",
    name: "Bebe",
    realName: "Cheng Bo-Wei",
    region: "PCS",
    role: "Bot",
    team: "Taipei Assassins",
    country: "🇹🇼",
    active: false,
    debutYear: 2012,
    achievements: [
      ...rep("worlds_title", [2012], "Taipei Assassins"),
      ...rep("regional_title", [2012], "Taipei Assassins"),
    ],
  },
  {
    id: "mistake",
    name: "MiSTakE",
    realName: "Chen Hui-Chung",
    region: "PCS",
    role: "Support",
    team: "Taipei Assassins",
    country: "🇹🇼",
    active: false,
    debutYear: 2012,
    blurb: "Captain of the 2012 world champion Taipei Assassins.",
    achievements: [
      ...rep("worlds_title", [2012], "Taipei Assassins"),
      ...rep("regional_title", [2012], "Taipei Assassins"),
    ],
  },
  {
    id: "maple",
    name: "Maple",
    realName: "Huang Yi-Tang",
    region: "PCS",
    role: "Mid",
    team: "PSG Talon",
    country: "🇹🇼",
    active: true,
    debutYear: 2014,
    blurb: "Flash Wolves' mid in the 'Korea slayer' era that repeatedly toppled SKT.",
    achievements: [
      ...rep("regional_title", [2016, 2017, 2018], "Flash Wolves"),
    ],
  },
  {
    id: "swordart",
    name: "SwordArt",
    realName: "Hu Shuo-Chieh",
    region: "PCS",
    role: "Support",
    team: "Vikings Esports",
    country: "🇹🇼",
    active: false,
    debutYear: 2013,
    blurb: "Flash Wolves icon who captained Suning to the 2020 Worlds final.",
    achievements: [
      ...rep("regional_title", [2016, 2017, 2018], "Flash Wolves"),
      ...rep("worlds_runnerup", [2020], "Suning"),
    ],
  },

  // ───────────────────────── VCS (Vietnam) ─────────────────────────
  {
    id: "levi",
    name: "Levi",
    realName: "Đỗ Duy Khánh",
    region: "VCS",
    role: "Jungle",
    team: "GAM Esports",
    country: "🇻🇳",
    active: false,
    debutYear: 2013,
    blurb: "Vietnam's most decorated player and the face of the GAM dynasty.",
    achievements: [
      ...rep("regional_title", [2017, 2018, 2019, 2020, 2022, 2023], "GAM Esports"),
    ],
  },

  // ───────────────────────── LJL (Japan) ─────────────────────────
  {
    id: "evi",
    name: "Evi",
    realName: "Shunsuke Murase",
    region: "LJL",
    role: "Top",
    team: "Fukuoka SoftBank Hawks",
    country: "🇯🇵",
    active: true,
    debutYear: 2015,
    blurb: "DFM cornerstone — drove Japan's first Worlds main-stage appearance in 2021.",
    achievements: [
      ...rep("regional_title", [2019, 2021, 2022, 2023], "DetonatioN FocusMe"),
    ],
  },
  {
    id: "yutapon",
    name: "Yutapon",
    realName: "Yuta Sugiura",
    region: "LJL",
    role: "Bot",
    team: "DetonatioN FocusMe",
    country: "🇯🇵",
    active: false,
    debutYear: 2013,
    blurb: "Veteran DFM marksman and multi-time LJL champion.",
    achievements: [
      ...rep("regional_title", [2019, 2021, 2022, 2023], "DetonatioN FocusMe"),
    ],
  },

  // ───────────────────────── CBLOL (Brazil) ─────────────────────────
  {
    id: "robo",
    name: "Robo",
    realName: "Leonardo Souza",
    region: "CBLOL",
    role: "Top",
    team: "paiN Gaming",
    country: "🇧🇷",
    active: true,
    debutYear: 2014,
    blurb: "The most decorated player in CBLOL history — seven domestic titles.",
    achievements: [
      ...rep("regional_title", [2017, 2018, 2021, 2022, 2023, 2023, 2024], "LOUD"),
    ],
  },
  {
    id: "tinowns",
    name: "tinowns",
    realName: "Thiago Sartori",
    region: "CBLOL",
    role: "Mid",
    team: "paiN Gaming",
    country: "🇧🇷",
    active: true,
    debutYear: 2016,
    blurb: "Architect of LOUD's CBLOL four-peat.",
    achievements: [
      ...rep("regional_title", [2017, 2022, 2023, 2023, 2024, 2024], "LOUD"),
    ],
  },
  {
    id: "brtt",
    name: "brTT",
    realName: "Felipe Gonçalves",
    region: "CBLOL",
    role: "Bot",
    team: "LOS",
    country: "🇧🇷",
    active: false,
    debutYear: 2012,
    blurb: "Brazil's most iconic marksman — six CBLOL titles across a 12-year career.",
    achievements: [
      ...rep("regional_title", [2013, 2014, 2015, 2017, 2019, 2021], "RED Canids"),
    ],
  },

  // ───────────────────────── LLA (Latin America) ─────────────────────────
  {
    id: "josedeodo",
    name: "Josedeodo",
    realName: "Brandon Joel Villegas",
    region: "LLA",
    role: "Jungle",
    team: "Estral Esports",
    country: "🇦🇷",
    active: true,
    debutYear: 2019,
    blurb: "LLA's breakout star — the first Latin American to earn a marquee NA contract.",
    achievements: [
      ...rep("regional_title", [2020, 2020, 2024], "Rainbow7 / Estral"),
    ],
  },
  {
    id: "seiya",
    name: "Seiya",
    realName: "Édgar Ali Bracamontes",
    region: "LLA",
    role: "Mid",
    team: "Isurus",
    country: "🇲🇽",
    active: true,
    debutYear: 2013,
    blurb: "The most decorated mid laner in Latin American history.",
    achievements: [
      ...rep("regional_title", [2014, 2015, 2016, 2017, 2018, 2019, 2021, 2022], "LATAM"),
    ],
  },

  // ───────────── additions: missing top-tier players & world champions ─────────────
  {
    id: "meiko",
    name: "Meiko",
    realName: "Tian Ye",
    region: "LPL",
    role: "Support",
    team: "Invictus Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2015,
    blurb: "MSI 2015 and Worlds 2021 champion — a defining LPL support.",
    achievements: [
      ...rep("worlds_title", [2021], "EDward Gaming"),
      ...rep("msi_title", [2015], "EDward Gaming"),
      ...rep("regional_title", [2015, 2016, 2017, 2021], "EDward Gaming"),
      ...rep("all_pro_1", [2021], "EDward Gaming"),
    ],
  },
  {
    id: "pawn",
    name: "PawN",
    realName: "Heo Won-seok",
    region: "LCK",
    role: "Mid",
    team: "KingZone DragonX",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    blurb: "Outdueled Faker en route to the 2014 world title; later an MSI champion.",
    achievements: [
      ...rep("worlds_title", [2014], "Samsung White"),
      ...rep("msi_title", [2015], "EDward Gaming"),
    ],
  },
  {
    id: "mlxg",
    name: "Mlxg",
    realName: "Liu Shi-Yu",
    region: "LPL",
    role: "Jungle",
    team: "Royal Never Give Up",
    country: "🇨🇳",
    active: false,
    debutYear: 2015,
    blurb: "RNG's beloved engine — MSI 2018 champion.",
    achievements: [
      ...rep("msi_title", [2018], "RNG"),
      ...rep("regional_title", [2016, 2018, 2018], "RNG"),
      ...rep("all_pro_1", [2017, 2018], "RNG"),
    ],
  },
  {
    id: "clearlove",
    name: "Clearlove",
    realName: "Ming Kai",
    region: "LPL",
    role: "Jungle",
    team: "EDward Gaming",
    country: "🇨🇳",
    active: false,
    debutYear: 2012,
    blurb: "'LPL Player No.001' — five-time domestic champion and MSI winner.",
    achievements: [
      ...rep("msi_title", [2015], "EDward Gaming"),
      ...rep("regional_title", [2014, 2014, 2015, 2016, 2017], "EDward Gaming"),
      ...rep("all_pro_1", [2015, 2016], "EDward Gaming"),
    ],
  },
  {
    id: "crown",
    name: "Crown",
    realName: "Lee Min-ho",
    region: "LCK",
    role: "Mid",
    team: "CLG",
    country: "🇰🇷",
    active: false,
    debutYear: 2015,
    blurb: "2017 world champion mid for Samsung Galaxy.",
    achievements: [
      ...rep("worlds_title", [2017], "Samsung Galaxy"),
      ...rep("worlds_runnerup", [2016], "Samsung Galaxy"),
    ],
  },
  {
    id: "cuvee",
    name: "CuVee",
    realName: "Lee Seong-jin",
    region: "LCK",
    role: "Top",
    team: "Gen.G",
    country: "🇰🇷",
    active: false,
    debutYear: 2014,
    blurb: "2017 world champion top laner for Samsung Galaxy.",
    achievements: [
      ...rep("worlds_title", [2017], "Samsung Galaxy"),
      ...rep("worlds_runnerup", [2016], "Samsung Galaxy"),
      ...rep("all_pro_1", [2017], "Samsung Galaxy"),
    ],
  },
  {
    id: "ambition",
    name: "Ambition",
    realName: "Kang Chan-yong",
    region: "LCK",
    role: "Jungle",
    team: "Gen.G",
    country: "🇰🇷",
    active: false,
    debutYear: 2012,
    blurb: "The veteran who captained Samsung Galaxy to the 2017 world title.",
    achievements: [
      ...rep("worlds_title", [2017], "Samsung Galaxy"),
      ...rep("worlds_runnerup", [2016], "Samsung Galaxy"),
    ],
  },
  {
    id: "pyosik",
    name: "Pyosik",
    realName: "Hong Chang-hyeon",
    region: "LCK",
    role: "Jungle",
    team: "DN Freecs",
    country: "🇰🇷",
    active: true,
    debutYear: 2019,
    blurb: "2022 world champion on DRX's miracle run.",
    achievements: [
      ...rep("worlds_title", [2022], "DRX"),
      ...rep("worlds_runnerup", [2025], "KT Rolster"),
    ],
  },
  {
    id: "kingen",
    name: "Kingen",
    realName: "Hwang Seong-hoon",
    region: "LCK",
    role: "Top",
    team: "Nongshim RedForce",
    country: "🇰🇷",
    active: true,
    debutYear: 2017,
    blurb: "2022 Worlds Finals MVP for DRX.",
    achievements: [
      ...rep("worlds_title", [2022], "DRX"),
      mvp("worlds_mvp", 2022, 1.0, "DRX"),
      ...rep("regional_title", [2018], "KT Rolster"),
    ],
  },
  {
    id: "peyz",
    name: "Peyz",
    realName: "Kim Su-hwan",
    region: "LCK",
    role: "Bot",
    team: "T1",
    country: "🇰🇷",
    active: true,
    debutYear: 2023,
    blurb: "MSI 2024 champion ADC; signed with T1 for 2026.",
    achievements: [
      ...rep("msi_title", [2024], "Gen.G"),
      ...rep("regional_title", [2023, 2023, 2024], "Gen.G"),
      ...rep("all_pro_1", [2024], "Gen.G"),
    ],
  },
  {
    id: "elk",
    name: "Elk",
    realName: "Zhao Jia-Hao",
    region: "LPL",
    role: "Bot",
    team: "Weibo Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2019,
    blurb: "Worlds 2024 finalist ADC for Bilibili Gaming.",
    achievements: [
      ...rep("regional_title", [2024, 2024, 2025], "Bilibili Gaming"),
      ...rep("worlds_runnerup", [2024], "Bilibili Gaming"),
      ...rep("all_pro_1", [2024], "Bilibili Gaming"),
    ],
  },

  // ───────────── expansion: more LCK legends & fan favorites ─────────────
  {
    id: "smeb",
    name: "Smeb",
    realName: "Song Kyung-ho",
    region: "LCK",
    role: "Top",
    team: "KT Rolster",
    country: "🇰🇷",
    active: false,
    debutYear: 2014,
    blurb: "The world's best top laner in 2016 and a ROX Tigers icon.",
    achievements: [
      ...rep("worlds_runnerup", [2015], "KOO Tigers"),
      ...rep("regional_title", [2016], "ROX Tigers"),
      mvp("season_mvp", 2016, 0.8, "ROX Tigers"),
      mvp("season_mvp", 2016, 0.7, "ROX Tigers"),
      ...rep("all_pro_1", [2016], "ROX Tigers"),
    ],
  },
  {
    id: "bdd",
    name: "Bdd",
    realName: "Gwak Bo-seong",
    region: "LCK",
    role: "Mid",
    team: "KT Rolster",
    country: "🇰🇷",
    active: true,
    debutYear: 2016,
    blurb: "Four-time LCK MVP; the great uncrowned mid until 2025's final.",
    achievements: [
      ...rep("worlds_runnerup", [2025], "KT Rolster"),
      ...rep("regional_title", [2017], "Longzhu"),
      mvp("season_mvp", 2017, 0.7, "Longzhu"),
      mvp("season_mvp", 2018, 0.7, "Kingzone"),
      mvp("season_mvp", 2020, 0.8, "Gen.G"),
      mvp("season_mvp", 2020, 0.6, "Gen.G"),
      ...rep("all_pro_1", [2017, 2018, 2020], "Longzhu / Gen.G"),
    ],
  },
  {
    id: "teddy",
    name: "Teddy",
    realName: "Park Jin-seong",
    region: "LCK",
    role: "Bot",
    team: "OKSavingsBank BRION",
    country: "🇰🇷",
    active: true,
    debutYear: 2017,
    blurb: "Fan-favorite marksman and back-to-back LCK champion with T1.",
    achievements: [
      ...rep("regional_title", [2019, 2020], "T1"),
      ...rep("all_pro_1", [2019], "T1"),
    ],
  },
  {
    id: "score",
    name: "Score",
    realName: "Go Dong-bin",
    region: "LCK",
    role: "Jungle",
    team: "KT Rolster",
    country: "🇰🇷",
    active: false,
    debutYear: 2012,
    blurb: "'The Immortal' — KT's beloved veteran, an LCK champion at last in 2018.",
    achievements: [
      ...rep("regional_title", [2018], "KT Rolster"),
      ...rep("all_pro_1", [2018], "KT Rolster"),
    ],
  },
  {
    id: "clid",
    name: "Clid",
    realName: "Kim Tae-min",
    region: "LCK",
    role: "Jungle",
    team: "Hanwha Life",
    country: "🇰🇷",
    active: false,
    debutYear: 2017,
    blurb: "SKT's 2019 jungle ace and LCK Summer Finals MVP.",
    achievements: [
      ...rep("regional_title", [2019], "T1"),
      mvp("finals_mvp", 2019, 0.8, "T1"),
      ...rep("all_pro_1", [2019], "T1"),
    ],
  },
  {
    id: "lehends",
    name: "Lehends",
    realName: "Son Si-woo",
    region: "LCK",
    role: "Support",
    team: "Gen.G",
    country: "🇰🇷",
    active: true,
    debutYear: 2018,
    blurb: "MSI 2024 champion support and two-time LCK MVP.",
    achievements: [
      ...rep("msi_title", [2024], "Gen.G"),
      ...rep("regional_title", [2024, 2024], "Gen.G"),
      mvp("season_mvp", 2023, 0.6, "Gen.G"),
      ...rep("all_pro_1", [2023, 2024], "Gen.G"),
    ],
  },
  {
    id: "cuzz",
    name: "Cuzz",
    realName: "Moon Woo-chan",
    region: "LCK",
    role: "Jungle",
    team: "KT Rolster",
    country: "🇰🇷",
    active: true,
    debutYear: 2016,
    blurb: "Durable jungle workhorse — an LCK champion across three orgs.",
    achievements: [
      ...rep("regional_title", [2017, 2018, 2020], "Longzhu / Kingzone / T1"),
    ],
  },
  {
    id: "effort",
    name: "Effort",
    realName: "Lee Sang-ho",
    region: "LCK",
    role: "Support",
    team: "KT Rolster",
    country: "🇰🇷",
    active: true,
    debutYear: 2017,
    blurb: "T1's support during the 2019–20 domestic double.",
    achievements: [
      ...rep("regional_title", [2019, 2020], "T1"),
    ],
  },
  {
    id: "kuro",
    name: "Kuro",
    realName: "Lee Seo-haeng",
    region: "LCK",
    role: "Mid",
    team: "ROX Tigers",
    country: "🇰🇷",
    active: false,
    debutYear: 2015,
    blurb: "The steady hand of the legendary ROX Tigers.",
    achievements: [
      ...rep("worlds_runnerup", [2015], "KOO Tigers"),
      ...rep("regional_title", [2016], "ROX Tigers"),
    ],
  },
  {
    id: "rascal",
    name: "Rascal",
    realName: "Kim Kwang-hee",
    region: "LCK",
    role: "Top",
    team: "DRX",
    country: "🇰🇷",
    active: false,
    debutYear: 2016,
    blurb: "The LCK's premier solo-kill top laner.",
    achievements: [
      ...rep("regional_title", [2017], "Longzhu"),
    ],
  },

  // ───────────── expansion: more LPL legends & fan favorites ─────────────
  {
    id: "gala",
    name: "GALA",
    realName: "Chen Wei",
    region: "LPL",
    role: "Bot",
    team: "JD Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2018,
    blurb: "Two-time MSI champion and 2021 MSI MVP.",
    achievements: [
      ...rep("msi_title", [2021, 2022], "RNG"),
      mvp("msi_mvp", 2021, 1.0, "RNG"),
      ...rep("regional_title", [2021, 2022], "RNG"),
      ...rep("all_pro_1", [2021], "RNG"),
    ],
  },
  {
    id: "duke",
    name: "Duke",
    realName: "Lee Ho-seong",
    region: "LPL",
    role: "Top",
    team: "Invictus Gaming",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    blurb: "Won Worlds with both SKT (2016) and Invictus Gaming (2018).",
    achievements: [
      ...rep("worlds_title", [2016], "SKT T1"),
      { type: "worlds_title", year: 2018, team: "Invictus Gaming", part: 0.5 },
      ...rep("regional_title", [2019], "Invictus Gaming"),
    ],
  },
  {
    id: "gimgoon",
    name: "GimGoon",
    realName: "Kim Han-saem",
    region: "LPL",
    role: "Top",
    team: "FunPlus Phoenix",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    blurb: "World champion top laner with FPX in 2019.",
    achievements: [
      ...rep("worlds_title", [2019], "FunPlus Phoenix"),
      ...rep("regional_title", [2019], "FPX"),
    ],
  },
  {
    id: "lwx",
    name: "Lwx",
    realName: "Lin Wei-Xiang",
    region: "LPL",
    role: "Bot",
    team: "Royal Never Give Up",
    country: "🇨🇳",
    active: false,
    debutYear: 2016,
    blurb: "FPX's world champion marksman.",
    achievements: [
      ...rep("worlds_title", [2019], "FunPlus Phoenix"),
      ...rep("regional_title", [2019], "FPX"),
    ],
  },
  {
    id: "baolan",
    name: "Baolan",
    realName: "Wang Liu-Yi",
    region: "LPL",
    role: "Support",
    team: "Rare Atom",
    country: "🇨🇳",
    active: false,
    debutYear: 2016,
    blurb: "Support on Invictus Gaming's 2018 world title.",
    achievements: [
      ...rep("worlds_title", [2018], "Invictus Gaming"),
      ...rep("regional_title", [2019], "Invictus Gaming"),
    ],
  },
  {
    id: "flandre",
    name: "Flandre",
    realName: "Li Xuan-Jun",
    region: "LPL",
    role: "Top",
    team: "Anyone's Legend",
    country: "🇨🇳",
    active: true,
    debutYear: 2014,
    blurb: "World champion in 2021; back in a Worlds final in 2025.",
    achievements: [
      ...rep("worlds_title", [2021], "EDward Gaming"),
      ...rep("worlds_runnerup", [2025], "Anyone's Legend"),
      ...rep("regional_title", [2021, 2025], "EDG / Anyone's Legend"),
    ],
  },
  {
    id: "on",
    name: "ON",
    realName: "Luo Wen-Jun",
    region: "LPL",
    role: "Support",
    team: "Bilibili Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2019,
    blurb: "BLG's support — 2024 Worlds finalist and 2026 First Stand champion.",
    achievements: [
      ...rep("first_stand_title", [2026], "Bilibili Gaming"),
      ...rep("worlds_runnerup", [2024], "Bilibili Gaming"),
      ...rep("regional_title", [2024, 2024, 2025, 2026], "Bilibili Gaming"),
    ],
  },
  {
    id: "xun",
    name: "Xun",
    realName: "Peng Li-Xun",
    region: "LPL",
    role: "Jungle",
    team: "Bilibili Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2020,
    blurb: "BLG's jungler — 2024 Worlds finalist and 2026 First Stand champion.",
    achievements: [
      ...rep("first_stand_title", [2026], "Bilibili Gaming"),
      ...rep("worlds_runnerup", [2024], "Bilibili Gaming"),
      ...rep("regional_title", [2024, 2024, 2026], "Bilibili Gaming"),
    ],
  },
  {
    id: "369",
    name: "369",
    realName: "Bai Jia-Hao",
    region: "LPL",
    role: "Top",
    team: "Top Esports",
    country: "🇨🇳",
    active: true,
    debutYear: 2018,
    blurb: "MSI 2023 champion; a perennial LPL title contender.",
    achievements: [
      ...rep("msi_title", [2023], "JD Gaming"),
      ...rep("msc_title", [2020], "Top Esports"),
      ...rep("regional_title", [2020, 2022, 2023, 2023, 2025], "TES / JDG"),
    ],
  },
  {
    id: "missing",
    name: "Missing",
    realName: "Lou Yun-Feng",
    region: "LPL",
    role: "Support",
    team: "LNG Esports",
    country: "🇨🇳",
    active: true,
    debutYear: 2018,
    blurb: "MSI 2023 champion support with JD Gaming.",
    achievements: [
      ...rep("msi_title", [2023], "JD Gaming"),
      ...rep("regional_title", [2022, 2023, 2023], "JD Gaming"),
    ],
  },
  {
    id: "yagao",
    name: "Yagao",
    realName: "Zeng Qi",
    region: "LPL",
    role: "Mid",
    team: "Bilibili Gaming",
    country: "🇨🇳",
    active: false,
    debutYear: 2017,
    blurb: "JDG's steady mid through their golden era.",
    achievements: [
      ...rep("regional_title", [2020, 2022], "JD Gaming"),
      mvp("finals_mvp", 2022, 0.6, "JD Gaming"),
    ],
  },
  {
    id: "cryin",
    name: "Cryin",
    realName: "Yuan Cheng-Wei",
    region: "LPL",
    role: "Mid",
    team: "EDward Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2018,
    blurb: "MSI 2021 champion mid.",
    achievements: [
      ...rep("msi_title", [2021], "RNG"),
      ...rep("regional_title", [2021], "RNG"),
    ],
  },
  {
    id: "light",
    name: "Light",
    realName: "Wang Guang-Yu",
    region: "LPL",
    role: "Bot",
    team: "Weibo Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2017,
    blurb: "Explosive fan-favorite marksman; 2023 Worlds finalist.",
    achievements: [
      ...rep("worlds_runnerup", [2023], "Weibo Gaming"),
    ],
  },
  {
    id: "tarzan",
    name: "Tarzan",
    realName: "Lee Seung-yong",
    region: "LPL",
    role: "Jungle",
    team: "Anyone's Legend",
    country: "🇰🇷",
    active: true,
    debutYear: 2017,
    blurb: "LPL champion and MVP; one of the region's most beloved junglers.",
    achievements: [
      ...rep("regional_title", [2025], "Anyone's Legend"),
      mvp("finals_mvp", 2025, 0.8, "Anyone's Legend"),
      mvp("season_mvp", 2026, 0.6, "Anyone's Legend"),
    ],
  },

  // ───────────── expansion: VCS ─────────────
  {
    id: "sofm",
    name: "SofM",
    realName: "Lê Quang Duy",
    region: "VCS",
    role: "Jungle",
    team: "MVK Esports",
    country: "🇻🇳",
    active: true,
    debutYear: 2013,
    blurb: "Trailblazing Vietnamese jungler; 2020 Worlds finalist with Suning.",
    achievements: [
      ...rep("worlds_runnerup", [2020], "Suning"),
    ],
  },
  {
    id: "optimus",
    name: "Optimus",
    realName: "Trần Văn Cường",
    region: "VCS",
    role: "Mid",
    team: "GAM Esports",
    country: "🇻🇳",
    active: true,
    debutYear: 2013,
    blurb: "GIGABYTE Marines' mid on Vietnam's iconic 2017 Worlds run.",
    achievements: [
      ...rep("regional_title", [2017, 2017], "GAM Esports"),
    ],
  },
  {
    id: "kiaya",
    name: "Kiaya",
    realName: "Trần Duy Sang",
    region: "VCS",
    role: "Top",
    team: "GAM Esports",
    country: "🇻🇳",
    active: true,
    debutYear: 2017,
    blurb: "GAM's veteran top laner and multi-time VCS champion.",
    achievements: [
      ...rep("regional_title", [2022, 2023, 2023, 2024], "GAM Esports"),
    ],
  },

  // ───────────── expansion: PCS ─────────────
  {
    id: "westdoor",
    name: "Westdoor",
    realName: "Liu Shu-Wei",
    region: "PCS",
    role: "Mid",
    team: "ahq e-Sports",
    country: "🇹🇼",
    active: false,
    debutYear: 2012,
    blurb: "ahq's iconic assassin specialist — a face of Taiwanese League.",
    achievements: [
      ...rep("regional_title", [2013], "ahq e-Sports"),
    ],
  },
  {
    id: "ziv",
    name: "Ziv",
    realName: "Chen Yi",
    region: "PCS",
    role: "Top",
    team: "ahq e-Sports",
    country: "🇹🇼",
    active: false,
    debutYear: 2015,
    blurb: "Long regarded the LMS's best top laner.",
    achievements: [
      ...rep("regional_title", [2015, 2016], "ahq e-Sports"),
    ],
  },
  {
    id: "betty",
    name: "Betty",
    realName: "Lu Yu-Hung",
    region: "PCS",
    role: "Bot",
    team: "PSG Talon",
    country: "🇹🇼",
    active: true,
    debutYear: 2016,
    blurb: "Flash Wolves core and a decorated Pacific marksman.",
    achievements: [
      ...rep("regional_title", [2017, 2017, 2018, 2018], "Flash Wolves"),
      ...rep("regional_title", [2024], "PSG Talon"),
    ],
  },
  {
    id: "doggo",
    name: "Doggo",
    realName: "Chiu Tzu-Chuan",
    region: "PCS",
    role: "Bot",
    team: "CTBC Flying Oyster",
    country: "🇹🇼",
    active: true,
    debutYear: 2019,
    blurb: "PSG Talon's MSI 2021 breakout; a modern Pacific star.",
    achievements: [
      ...rep("regional_title", [2025, 2025], "CTBC Flying Oyster"),
    ],
  },

  // ───────────── expansion: LJL (DetonatioN FocusMe dynasty) ─────────────
  {
    id: "ceros",
    name: "Ceros",
    realName: "Kyohei Yoshida",
    region: "LJL",
    role: "Mid",
    team: "DetonatioN FocusMe",
    country: "🇯🇵",
    active: false,
    debutYear: 2013,
    blurb: "Among the most decorated players in LJL history.",
    achievements: [
      ...rep("regional_title", [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2021, 2022], "DetonatioN FocusMe"),
    ],
  },
  {
    id: "steal",
    name: "Steal",
    realName: "Mun Geon-yeong",
    region: "LJL",
    role: "Jungle",
    team: "DetonatioN FocusMe",
    country: "🇰🇷",
    active: false,
    debutYear: 2015,
    blurb: "DFM's jungler through Japan's historic Worlds runs.",
    achievements: [
      ...rep("regional_title", [2021, 2021, 2022, 2022, 2023, 2023, 2024], "DetonatioN FocusMe"),
    ],
  },
  {
    id: "paz",
    name: "Paz",
    realName: "Shirou Sasaki",
    region: "LJL",
    role: "Top",
    team: "DetonatioN FocusMe",
    country: "🇯🇵",
    active: false,
    debutYear: 2014,
    blurb: "Veteran DFM top laner of the LJL dynasty.",
    achievements: [
      ...rep("regional_title", [2019, 2021, 2022, 2023, 2023], "DetonatioN FocusMe"),
    ],
  },

  // ───────────── expansion: CBLOL ─────────────
  {
    id: "kami",
    name: "Kami",
    realName: "Gabriel Bohm",
    region: "CBLOL",
    role: "Mid",
    team: "paiN Gaming",
    country: "🇧🇷",
    active: false,
    debutYear: 2011,
    blurb: "Brazil's original superstar mid and paiN Gaming icon.",
    achievements: [
      ...rep("regional_title", [2013, 2015], "paiN Gaming"),
    ],
  },
  {
    id: "revolta",
    name: "Revolta",
    realName: "Gabriel Henud",
    region: "CBLOL",
    role: "Jungle",
    team: "INTZ",
    country: "🇧🇷",
    active: true,
    debutYear: 2012,
    blurb: "CBLOL's 'Exodia' jungler — part of INTZ's historic 2016 win over EDG.",
    achievements: [
      ...rep("regional_title", [2015, 2016, 2016], "INTZ"),
    ],
  },
  {
    id: "micao",
    name: "micaO",
    realName: "Micael Rodrigues",
    region: "CBLOL",
    role: "Bot",
    team: "INTZ",
    country: "🇧🇷",
    active: true,
    debutYear: 2014,
    blurb: "Four-time CBLOL champion marksman.",
    achievements: [
      ...rep("regional_title", [2015, 2016, 2016, 2020], "INTZ"),
    ],
  },

  // ───────────── expansion: LLA ─────────────
  {
    id: "whitelotus",
    name: "WhiteLotus",
    realName: "Matías Musso",
    region: "LLA",
    role: "Bot",
    team: "Infinity Esports",
    country: "🇺🇾",
    active: true,
    debutYear: 2014,
    blurb: "The only player to win a title in every Latin American league.",
    achievements: [
      ...rep("regional_title", [2015, 2017, 2017, 2019, 2021, 2021], "Lyon / Infinity"),
    ],
  },
  {
    id: "oddie",
    name: "Oddie",
    realName: "Sebastián Niño",
    region: "LLA",
    role: "Jungle",
    team: "Fuego",
    country: "🇲🇽",
    active: true,
    debutYear: 2017,
    blurb: "A region-defining LLA jungler and fan favorite.",
    achievements: [
      ...rep("regional_title", [2021, 2023, 2024, 2024], "Rainbow7 / Estral"),
    ],
  },

  // ───────────── expansion: LEC legends & stars ─────────────
  {
    id: "xpeke",
    name: "xPeke",
    realName: "Enrique Cedeño Martínez",
    region: "LEC",
    role: "Mid",
    team: "Origen",
    country: "🇪🇸",
    active: false,
    debutYear: 2010,
    blurb: "Season 1 world champion and a founding legend of European League.",
    achievements: [
      ...rep("worlds_title", [2011], "Fnatic"),
      ...rep("regional_title", [2013, 2013, 2014], "Fnatic"),
    ],
  },
  {
    id: "soaz",
    name: "sOAZ",
    realName: "Paul Boyer",
    region: "LEC",
    role: "Top",
    team: "Fnatic",
    country: "🇫🇷",
    active: false,
    debutYear: 2010,
    blurb: "France's foundational top laner; multiple Worlds finals.",
    achievements: [
      ...rep("worlds_runnerup", [2011, 2018], "aAa / Fnatic"),
      ...rep("regional_title", [2013, 2013, 2014, 2018], "Fnatic"),
    ],
  },
  {
    id: "febiven",
    name: "Febiven",
    realName: "Fabian Diepstraten",
    region: "LEC",
    role: "Mid",
    team: "Fnatic",
    country: "🇳🇱",
    active: false,
    debutYear: 2014,
    blurb: "Mid of Fnatic's famous 18–0 split in 2015.",
    achievements: [
      ...rep("regional_title", [2015, 2015], "Fnatic"),
    ],
  },
  {
    id: "wunder",
    name: "Wunder",
    realName: "Martin Hansen",
    region: "LEC",
    role: "Top",
    team: "SK Gaming",
    country: "🇩🇰",
    active: true,
    debutYear: 2015,
    blurb: "MSI 2019 champion and Worlds finalist with G2.",
    achievements: [
      ...rep("msi_title", [2019], "G2 Esports"),
      ...rep("worlds_runnerup", [2019], "G2 Esports"),
      ...rep("regional_title", [2019, 2019, 2020, 2020], "G2 Esports"),
    ],
  },
  {
    id: "humanoid",
    name: "Humanoid",
    realName: "Marek Brázda",
    region: "LEC",
    role: "Mid",
    team: "Team Vitality",
    country: "🇨🇿",
    active: true,
    debutYear: 2018,
    blurb: "Two-time LEC champion mid with MAD Lions.",
    achievements: [
      ...rep("regional_title", [2021, 2021], "MAD Lions"),
    ],
  },
  {
    id: "brokenblade",
    name: "BrokenBlade",
    realName: "Sergen Çelik",
    region: "LEC",
    role: "Top",
    team: "G2 Esports",
    country: "🇹🇷",
    active: true,
    debutYear: 2017,
    blurb: "G2's long-tenured top-lane cornerstone.",
    achievements: [
      ...rep("regional_title", [2022, 2023, 2024, 2024, 2025], "G2 Esports"),
    ],
  },
  {
    id: "elyoya",
    name: "Elyoya",
    realName: "Javier Prades",
    region: "LEC",
    role: "Jungle",
    team: "Movistar KOI",
    country: "🇪🇸",
    active: true,
    debutYear: 2020,
    blurb: "Spain's premier jungler; LEC champion and Finals MVP.",
    achievements: [
      ...rep("regional_title", [2021, 2021, 2024], "MAD Lions / KOI"),
      mvp("finals_mvp", 2025, 0.7, "Movistar KOI"),
    ],
  },
  {
    id: "canna",
    name: "Canna",
    realName: "Kim Chang-dong",
    region: "LEC",
    role: "Top",
    team: "Karmine Corp",
    country: "🇰🇷",
    active: true,
    debutYear: 2020,
    blurb: "LCK champion as a rookie with T1; now in the LEC.",
    achievements: [
      ...rep("regional_title", [2020], "T1"),
    ],
  },

  // ───────────── expansion: LCS legends & stars ─────────────
  {
    id: "sneaky",
    name: "Sneaky",
    realName: "Zachary Scuderi",
    region: "LCS",
    role: "Bot",
    team: "Cloud9",
    country: "🇺🇸",
    active: false,
    debutYear: 2013,
    blurb: "Cloud9's beloved marksman and a defining NA personality.",
    achievements: [
      ...rep("regional_title", [2014], "Cloud9"),
    ],
  },
  {
    id: "jensen",
    name: "Jensen",
    realName: "Nicolaj Jensen",
    region: "LCS",
    role: "Mid",
    team: "Team Liquid",
    country: "🇩🇰",
    active: false,
    debutYear: 2014,
    blurb: "Elite NA mid; MSI 2019 finalist with Team Liquid.",
    achievements: [
      ...rep("regional_title", [2019, 2019], "Team Liquid"),
      ...rep("regional_title", [2022], "Cloud9"),
    ],
  },
  {
    id: "aphromoo",
    name: "Aphromoo",
    realName: "Zaqueri Black",
    region: "LCS",
    role: "Support",
    team: "FlyQuest",
    country: "🇺🇸",
    active: false,
    debutYear: 2012,
    blurb: "First NA support to win league MVP; the 'Rush Hour' icon.",
    achievements: [
      ...rep("regional_title", [2015, 2016], "CLG"),
      mvp("season_mvp", 2018, 0.5, "100 Thieves"),
    ],
  },
  {
    id: "hauntzer",
    name: "Hauntzer",
    realName: "Kevin Yarnell",
    region: "LCS",
    role: "Top",
    team: "Shopify Rebellion",
    country: "🇺🇸",
    active: false,
    debutYear: 2014,
    blurb: "Top laner of TSM's dominant late-2010s run.",
    achievements: [
      ...rep("regional_title", [2016, 2017, 2017], "TSM"),
    ],
  },
  {
    id: "svenskeren",
    name: "Svenskeren",
    realName: "Dennis Johnsen",
    region: "LCS",
    role: "Jungle",
    team: "Cloud9",
    country: "🇩🇰",
    active: false,
    debutYear: 2012,
    blurb: "Two-time LCS champion jungler and 2019 LCS MVP.",
    achievements: [
      ...rep("regional_title", [2017, 2017], "TSM"),
      mvp("season_mvp", 2019, 0.6, "Cloud9"),
    ],
  },
  {
    id: "wildturtle",
    name: "WildTurtle",
    realName: "Jason Tran",
    region: "LCS",
    role: "Bot",
    team: "Shopify Rebellion",
    country: "🇨🇦",
    active: false,
    debutYear: 2013,
    blurb: "Long-running NA marksman fan favorite.",
    achievements: [
      ...rep("regional_title", [2013, 2014, 2015], "TSM"),
    ],
  },
  {
    id: "stixxay",
    name: "Stixxay",
    realName: "Trevor Hayes",
    region: "LCS",
    role: "Bot",
    team: "Golden Guardians",
    country: "🇺🇸",
    active: false,
    debutYear: 2015,
    blurb: "The rookie who took CLG to the MSI 2016 final.",
    achievements: [
      ...rep("regional_title", [2016], "CLG"),
    ],
  },
  {
    id: "berserker",
    name: "Berserker",
    realName: "Kim Min-cheol",
    region: "LCS",
    role: "Bot",
    team: "LYON",
    country: "🇰🇷",
    active: true,
    debutYear: 2022,
    blurb: "Rookie sensation; back-to-back LCS titles and 2022 Finals MVP.",
    achievements: [
      ...rep("regional_title", [2022, 2023], "Cloud9"),
      mvp("finals_mvp", 2022, 0.8, "Cloud9"),
    ],
  },
  {
    id: "bwipo",
    name: "Bwipo",
    realName: "Gabriël Rau",
    region: "LCS",
    role: "Top",
    team: "FlyQuest",
    country: "🇧🇪",
    active: true,
    debutYear: 2017,
    blurb: "Worlds 2018 finalist with Fnatic; later an LCS champion.",
    achievements: [
      ...rep("worlds_runnerup", [2018], "Fnatic"),
      ...rep("regional_title", [2018], "Fnatic"),
      ...rep("regional_title", [2024], "FlyQuest"),
    ],
  },
];

// Real honors synced from Leaguepedia (CC BY-SA) by scripts/ingest-leaguepedia.mjs are
// merged onto the curated bios ADDITIVELY: every curated honor is kept, and any synced
// honor not already present (matched on type+year+team) is added. This means a sync can
// only improve coverage, never silently drop a curated title the scraper doesn't fetch
// (e.g. EWC / Asian Games / First Stand). Empty file → the curated seed is used as-is.
const GENERATED = generatedAchievements as Record<string, Achievement[]>;

const achKey = (a: Achievement) => `${a.type}|${a.year}|${a.team ?? ""}`;

export const PLAYERS: Player[] = CURATED_PLAYERS.map((p) => {
  const synced = GENERATED[p.id];
  if (!synced || synced.length === 0) return p;
  const have = new Set(p.achievements.map(achKey));
  const extra = synced.filter((a) => !have.has(achKey(a)));
  return extra.length > 0 ? { ...p, achievements: [...p.achievements, ...extra] } : p;
});

// ───────────────────────── accessors ─────────────────────────

export function getPlayer(id: string): Player | undefined {
  return PLAYERS.find((p) => p.id === id);
}

export function filterPlayers(opts: { region?: Region | "ALL"; role?: Role | "ALL" }): Player[] {
  return PLAYERS.filter(
    (p) =>
      (!opts.region || opts.region === "ALL" || p.region === opts.region) &&
      (!opts.role || opts.role === "ALL" || p.role === opts.role)
  );
}
