import type { Achievement, AchievementType, Player, Region, Role } from "./types";
import { DEFAULT_WEIGHTS, honorScore, type Weights } from "./honor";
import generatedAchievements from "./players.generated.json";

export const DATA_NOTE =
  "Illustrative dataset for this prototype — honors are approximate and seeded by hand, not yet synced from Leaguepedia.";

const rep = (type: AchievementType, years: number[], team?: string): Achievement[] =>
  years.map((year) => ({ type, year, team }));

const mvp = (type: AchievementType, year: number, share: number, team?: string): Achievement => ({
  type,
  year,
  share,
  team,
});

const CURATED_PLAYERS: Player[] = [
  // ───────────────────────── LCK ─────────────────────────
  {
    id: "faker",
    name: "Faker",
    realName: "Lee Sang-hyeok",
    region: "LCK",
    role: "Mid",
    team: "T1",
    country: "🇰🇷",
    active: true,
    debutYear: 2013,
    blurb: "The Unkillable Demon King. The defining career of the sport.",
    achievements: [
      ...rep("worlds_title", [2013, 2015, 2016, 2023, 2024], "T1"),
      ...rep("msi_title", [2016, 2017], "T1"),
      ...rep("regional_title", [2013, 2015, 2016, 2019, 2022, 2023, 2024, 2025, 2015, 2016], "T1"),
      mvp("worlds_mvp", 2016, 1.0, "T1"),
      mvp("msi_mvp", 2017, 0.9, "T1"),
      mvp("season_mvp", 2015, 0.82, "T1"),
      mvp("season_mvp", 2019, 0.7, "T1"),
      ...rep("all_pro_1", [2015, 2016, 2017, 2019, 2021, 2023, 2024], "T1"),
      ...rep("all_pro_2", [2018, 2022], "T1"),
      ...rep("worlds_runnerup", [2017, 2022], "T1"),
    ],
  },
  {
    id: "showmaker",
    name: "ShowMaker",
    realName: "Heo Su",
    region: "LCK",
    role: "Mid",
    team: "Dplus KIA",
    country: "🇰🇷",
    active: true,
    debutYear: 2019,
    blurb: "Coronated at 2020 Worlds; the cleanest solo-queue mechanics of his era.",
    achievements: [
      ...rep("worlds_title", [2020], "DAMWON"),
      ...rep("regional_title", [2020, 2021], "DAMWON"),
      ...rep("worlds_runnerup", [2021], "DK"),
      mvp("season_mvp", 2020, 0.8, "DAMWON"),
      ...rep("all_pro_1", [2020, 2021, 2022], "DK"),
      ...rep("all_pro_2", [2023], "Dplus KIA"),
    ],
  },
  {
    id: "chovy",
    name: "Chovy",
    realName: "Jeong Ji-hoon",
    region: "LCK",
    role: "Mid",
    team: "Gen.G",
    country: "🇰🇷",
    active: true,
    debutYear: 2019,
    blurb: "Statistically dominant laner; the great 'uncrowned at Worlds' question.",
    achievements: [
      ...rep("msi_title", [2024], "Gen.G"),
      ...rep("regional_title", [2022, 2023, 2024, 2025, 2024], "Gen.G"),
      mvp("season_mvp", 2023, 0.78, "Gen.G"),
      mvp("season_mvp", 2024, 0.85, "Gen.G"),
      mvp("msi_mvp", 2024, 0.55, "Gen.G"),
      ...rep("all_pro_1", [2020, 2021, 2022, 2023, 2024, 2025], "Gen.G"),
    ],
  },
  {
    id: "zeus",
    name: "Zeus",
    realName: "Choi Woo-je",
    region: "LCK",
    role: "Top",
    team: "HLE",
    country: "🇰🇷",
    active: true,
    debutYear: 2022,
    blurb: "Two-time world champion top laner with carry-threat teleports.",
    achievements: [
      ...rep("worlds_title", [2023, 2024], "T1"),
      ...rep("regional_title", [2024, 2025], "T1"),
      ...rep("all_pro_1", [2023, 2024], "T1"),
      ...rep("all_pro_2", [2025], "HLE"),
    ],
  },
  {
    id: "oner",
    name: "Oner",
    realName: "Mun Hyeon-jun",
    region: "LCK",
    role: "Jungle",
    team: "T1",
    country: "🇰🇷",
    active: true,
    debutYear: 2021,
    achievements: [
      ...rep("worlds_title", [2023, 2024], "T1"),
      ...rep("regional_title", [2024, 2025], "T1"),
      ...rep("all_pro_1", [2023], "T1"),
      ...rep("all_pro_2", [2024], "T1"),
      ...rep("worlds_runnerup", [2022], "T1"),
    ],
  },
  {
    id: "gumayusi",
    name: "Gumayusi",
    realName: "Lee Min-hyeong",
    region: "LCK",
    role: "Bot",
    team: "T1",
    country: "🇰🇷",
    active: true,
    debutYear: 2021,
    achievements: [
      ...rep("worlds_title", [2023, 2024], "T1"),
      ...rep("regional_title", [2024, 2025], "T1"),
      ...rep("all_pro_1", [2024], "T1"),
      ...rep("all_pro_2", [2023], "T1"),
      ...rep("worlds_runnerup", [2022], "T1"),
    ],
  },
  {
    id: "keria",
    name: "Keria",
    realName: "Ryu Min-seok",
    region: "LCK",
    role: "Support",
    team: "T1",
    country: "🇰🇷",
    active: true,
    debutYear: 2020,
    blurb: "Generational support — defines the role's modern playmaking ceiling.",
    achievements: [
      ...rep("worlds_title", [2023, 2024], "T1"),
      ...rep("regional_title", [2024, 2025], "T1"),
      ...rep("all_pro_1", [2021, 2023, 2024, 2025], "T1"),
      ...rep("worlds_runnerup", [2022], "T1"),
    ],
  },
  {
    id: "beryl",
    name: "BeryL",
    realName: "Cho Geon-hee",
    region: "LCK",
    role: "Support",
    team: "Dplus KIA",
    country: "🇰🇷",
    active: true,
    debutYear: 2019,
    blurb: "Won Worlds with two different teams — the ultimate roster value pick.",
    achievements: [
      ...rep("worlds_title", [2020, 2022], "DAMWON / DRX"),
      ...rep("regional_title", [2020], "DAMWON"),
      ...rep("worlds_runnerup", [2021], "DK"),
      ...rep("all_pro_1", [2020], "DAMWON"),
      ...rep("all_pro_2", [2022], "DRX"),
    ],
  },
  {
    id: "deft",
    name: "Deft",
    realName: "Kim Hyuk-kyu",
    region: "LCK",
    role: "Bot",
    team: "KT Rolster",
    country: "🇰🇷",
    active: true,
    debutYear: 2013,
    blurb: "A decade of waiting, rewarded with the 2022 Worlds title.",
    achievements: [
      ...rep("worlds_title", [2022], "DRX"),
      ...rep("regional_title", [2015], "KT"),
      ...rep("all_pro_1", [2014, 2022], "KT / DRX"),
      ...rep("all_pro_2", [2015, 2021], "KT"),
    ],
  },
  {
    id: "canyon",
    name: "Canyon",
    realName: "Kim Geon-bu",
    region: "LCK",
    role: "Jungle",
    team: "Gen.G",
    country: "🇰🇷",
    active: true,
    debutYear: 2019,
    blurb: "Worlds champion jungler; widely rated the most complete of his generation.",
    achievements: [
      ...rep("worlds_title", [2020], "DAMWON"),
      ...rep("msi_title", [2024], "Gen.G"),
      ...rep("regional_title", [2020, 2021, 2024, 2025], "DAMWON / Gen.G"),
      ...rep("worlds_runnerup", [2021], "DK"),
      mvp("season_mvp", 2021, 0.8, "DK"),
      mvp("msi_mvp", 2024, 0.6, "Gen.G"),
      ...rep("all_pro_1", [2020, 2021, 2024], "DK / Gen.G"),
    ],
  },
  {
    id: "ruler",
    name: "Ruler",
    realName: "Park Jae-hyuk",
    region: "LCK",
    role: "Bot",
    team: "Gen.G",
    country: "🇰🇷",
    active: true,
    debutYear: 2016,
    blurb: "2017 Worlds Finals MVP; later an LPL champion. Cross-region résumé.",
    achievements: [
      ...rep("worlds_title", [2017], "Samsung"),
      ...rep("msi_title", [2024], "Gen.G"),
      ...rep("regional_title", [2022, 2023, 2023], "JDG / Gen.G"),
      mvp("worlds_mvp", 2017, 1.0, "Samsung"),
      mvp("season_mvp", 2023, 0.6, "JDG"),
      ...rep("all_pro_1", [2017, 2022, 2023, 2024], "Samsung / JDG / Gen.G"),
      ...rep("worlds_runnerup", [2016], "Samsung"),
    ],
  },

  // ───────────────────────── LPL ─────────────────────────
  {
    id: "uzi",
    name: "Uzi",
    realName: "Jian Zi-Hao",
    region: "LPL",
    role: "Bot",
    team: "RNG (retired)",
    country: "🇨🇳",
    active: false,
    debutYear: 2012,
    blurb: "The prodigy who carried a generation — MSI champion, never a Worlds title.",
    achievements: [
      ...rep("msi_title", [2018], "RNG"),
      ...rep("regional_title", [2016, 2018], "RNG"),
      mvp("msi_mvp", 2018, 1.0, "RNG"),
      mvp("season_mvp", 2018, 0.8, "RNG"),
      ...rep("all_pro_1", [2016, 2017, 2018, 2019], "RNG"),
      ...rep("worlds_runnerup", [2013], "Royal Club"),
    ],
  },
  {
    id: "jackeylove",
    name: "JackeyLove",
    realName: "Yu Wen-Bo",
    region: "LPL",
    role: "Bot",
    team: "TES",
    country: "🇨🇳",
    active: true,
    debutYear: 2017,
    achievements: [
      ...rep("worlds_title", [2018], "Invictus Gaming"),
      ...rep("regional_title", [2019, 2020, 2024], "IG / TES"),
      ...rep("all_pro_1", [2020, 2021, 2024], "TES"),
      mvp("season_mvp", 2021, 0.5, "TES"),
    ],
  },
  {
    id: "theshy",
    name: "TheShy",
    realName: "Kang Seung-lok",
    region: "LPL",
    role: "Top",
    team: "Weibo Gaming",
    country: "🇰🇷",
    active: true,
    debutYear: 2017,
    blurb: "2018 world champion known for the most aggressive top-lane ever.",
    achievements: [
      ...rep("worlds_title", [2018], "Invictus Gaming"),
      ...rep("regional_title", [2019], "IG"),
      ...rep("worlds_runnerup", [2024], "Weibo Gaming"),
      ...rep("all_pro_1", [2018, 2019, 2021], "IG"),
      ...rep("all_pro_2", [2024], "Weibo Gaming"),
    ],
  },
  {
    id: "rookie",
    name: "Rookie",
    realName: "Song Eui-jin",
    region: "LPL",
    role: "Mid",
    team: "Ninjas in Pyjamas",
    country: "🇰🇷",
    active: true,
    debutYear: 2014,
    achievements: [
      ...rep("worlds_title", [2018], "Invictus Gaming"),
      ...rep("regional_title", [2018, 2019], "IG"),
      mvp("season_mvp", 2017, 0.72, "IG"),
      mvp("season_mvp", 2018, 0.62, "IG"),
      ...rep("all_pro_1", [2017, 2018, 2019], "IG"),
    ],
  },
  {
    id: "knight",
    name: "knight",
    realName: "Zhuo Ding",
    region: "LPL",
    role: "Mid",
    team: "TES",
    country: "🇨🇳",
    active: true,
    debutYear: 2019,
    blurb: "Highest-ceiling LPL mid of the 2020s — still chasing the Worlds title.",
    achievements: [
      ...rep("regional_title", [2024, 2025], "TES"),
      ...rep("worlds_runnerup", [2025], "TES"),
      mvp("season_mvp", 2021, 0.8, "TES"),
      mvp("season_mvp", 2024, 0.85, "TES"),
      mvp("finals_mvp", 2024, 0.9, "TES"),
      ...rep("all_pro_1", [2021, 2024, 2025], "TES"),
    ],
  },
  {
    id: "xiaohu",
    name: "Xiaohu",
    realName: "Li Yuan-Hao",
    region: "LPL",
    role: "Mid",
    team: "RNG",
    country: "🇨🇳",
    active: true,
    debutYear: 2015,
    blurb: "Two-time MSI champion at the heart of the RNG dynasty.",
    achievements: [
      ...rep("msi_title", [2018, 2021], "RNG"),
      ...rep("regional_title", [2016, 2018, 2021, 2022], "RNG"),
      ...rep("all_pro_1", [2017, 2020, 2021], "RNG"),
    ],
  },
  {
    id: "ming",
    name: "Ming",
    realName: "Shi Sen-Ming",
    region: "LPL",
    role: "Support",
    team: "RNG",
    country: "🇨🇳",
    active: true,
    debutYear: 2016,
    achievements: [
      ...rep("msi_title", [2018, 2021], "RNG"),
      ...rep("regional_title", [2018, 2021], "RNG"),
      ...rep("all_pro_1", [2018, 2021, 2022], "RNG"),
    ],
  },
  {
    id: "scout",
    name: "Scout",
    realName: "Lee Ye-chan",
    region: "LPL",
    role: "Mid",
    team: "EDward Gaming",
    country: "🇰🇷",
    active: true,
    debutYear: 2016,
    achievements: [
      ...rep("worlds_title", [2021], "EDward Gaming"),
      ...rep("regional_title", [2020, 2021], "EDG"),
      mvp("season_mvp", 2020, 0.6, "EDG"),
      ...rep("all_pro_1", [2020, 2021], "EDG"),
    ],
  },
  {
    id: "jiejie",
    name: "JieJie",
    realName: "Zhao Li-Jie",
    region: "LPL",
    role: "Jungle",
    team: "TES",
    country: "🇨🇳",
    active: true,
    debutYear: 2020,
    achievements: [
      ...rep("worlds_title", [2021], "EDward Gaming"),
      ...rep("regional_title", [2021, 2024], "EDG / TES"),
      ...rep("all_pro_1", [2021, 2022], "EDG"),
      ...rep("worlds_runnerup", [2025], "TES"),
    ],
  },
  {
    id: "doinb",
    name: "Doinb",
    realName: "Kim Tae-sang",
    region: "LPL",
    role: "Mid",
    team: "FunPlus Phoenix",
    country: "🇰🇷",
    active: true,
    debutYear: 2015,
    achievements: [
      ...rep("worlds_title", [2019], "FunPlus Phoenix"),
      ...rep("regional_title", [2019], "FPX"),
      mvp("season_mvp", 2019, 1.0, "FPX"),
      ...rep("all_pro_1", [2019, 2020], "FPX"),
    ],
  },
  {
    id: "tian",
    name: "Tian",
    realName: "Gao Tian-Liang",
    region: "LPL",
    role: "Jungle",
    team: "FunPlus Phoenix",
    country: "🇨🇳",
    active: true,
    debutYear: 2018,
    achievements: [
      ...rep("worlds_title", [2019], "FunPlus Phoenix"),
      ...rep("regional_title", [2019], "FPX"),
      mvp("worlds_mvp", 2019, 1.0, "FPX"),
      ...rep("all_pro_1", [2019], "FPX"),
    ],
  },
  {
    id: "bin",
    name: "Bin",
    realName: "Chen Ze-Bin",
    region: "LPL",
    role: "Top",
    team: "Bilibili Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2019,
    blurb: "Carry top laner of the modern LPL; agonizingly close at 2024 Worlds.",
    achievements: [
      ...rep("regional_title", [2024, 2025], "BLG"),
      ...rep("worlds_runnerup", [2024], "Bilibili Gaming"),
      mvp("season_mvp", 2024, 0.7, "BLG"),
      ...rep("all_pro_1", [2024, 2025], "BLG"),
    ],
  },

  // ───────────────────────── LEC ─────────────────────────
  {
    id: "caps",
    name: "Caps",
    realName: "Rasmus Winther",
    region: "LEC",
    role: "Mid",
    team: "G2 Esports",
    country: "🇩🇰",
    active: true,
    debutYear: 2016,
    blurb: "The West's best — an MSI title and two Worlds finals appearances.",
    achievements: [
      ...rep("msi_title", [2019], "G2 Esports"),
      ...rep("regional_title", [2018, 2019, 2020, 2022, 2023, 2024, 2025, 2019], "Fnatic / G2"),
      ...rep("worlds_runnerup", [2018, 2019], "Fnatic / G2"),
      mvp("season_mvp", 2018, 0.7, "Fnatic"),
      mvp("season_mvp", 2022, 0.66, "G2"),
      ...rep("all_pro_1", [2018, 2019, 2020, 2022, 2023], "Fnatic / G2"),
    ],
  },
  {
    id: "jankos",
    name: "Jankos",
    realName: "Marcin Jankowski",
    region: "LEC",
    role: "Jungle",
    team: "GIANTX",
    country: "🇵🇱",
    active: true,
    debutYear: 2015,
    achievements: [
      ...rep("msi_title", [2019], "G2 Esports"),
      ...rep("regional_title", [2019, 2020, 2021], "G2"),
      ...rep("worlds_runnerup", [2019], "G2 Esports"),
      ...rep("all_pro_1", [2019, 2020], "G2"),
    ],
  },
  {
    id: "rekkles",
    name: "Rekkles",
    realName: "Martin Larsson",
    region: "LEC",
    role: "Bot",
    team: "Fnatic",
    country: "🇸🇪",
    active: true,
    debutYear: 2013,
    blurb: "The face of European bot lane for a decade.",
    achievements: [
      ...rep("regional_title", [2015, 2017, 2018, 2020, 2021], "Fnatic / G2"),
      ...rep("worlds_runnerup", [2018], "Fnatic"),
      ...rep("all_pro_1", [2017, 2018, 2019, 2020], "Fnatic"),
    ],
  },
  {
    id: "mikyx",
    name: "Mikyx",
    realName: "Mihael Mehle",
    region: "LEC",
    role: "Support",
    team: "G2 Esports",
    country: "🇸🇮",
    active: true,
    debutYear: 2016,
    achievements: [
      ...rep("msi_title", [2019], "G2 Esports"),
      ...rep("regional_title", [2019, 2020, 2024], "G2"),
      ...rep("worlds_runnerup", [2019], "G2 Esports"),
      ...rep("all_pro_1", [2019], "G2"),
    ],
  },

  // ───────────────────────── LCS ─────────────────────────
  {
    id: "bjergsen",
    name: "Bjergsen",
    realName: "Søren Bjerg",
    region: "LCS",
    role: "Mid",
    team: "TSM (retired)",
    country: "🇩🇰",
    active: false,
    debutYear: 2013,
    blurb: "North America's defining mid laner and serial domestic MVP.",
    achievements: [
      ...rep("regional_title", [2014, 2015, 2016, 2017, 2020], "TSM"),
      mvp("season_mvp", 2014, 0.9, "TSM"),
      mvp("season_mvp", 2016, 0.8, "TSM"),
      mvp("season_mvp", 2018, 0.78, "TSM"),
      mvp("season_mvp", 2020, 0.7, "TSM"),
      ...rep("all_pro_1", [2014, 2015, 2016, 2017, 2018, 2020], "TSM"),
    ],
  },
  {
    id: "doublelift",
    name: "Doublelift",
    realName: "Yiliang Peng",
    region: "LCS",
    role: "Bot",
    team: "TL (retired)",
    country: "🇺🇸",
    active: false,
    debutYear: 2011,
    blurb: "Eight-time domestic champion and the loudest carry NA ever produced.",
    achievements: [
      ...rep("regional_title", [2015, 2016, 2017, 2018, 2019, 2020], "CLG / TSM / TL"),
      mvp("season_mvp", 2018, 0.6, "TL"),
      ...rep("all_pro_1", [2015, 2016, 2018, 2019], "TSM / TL"),
    ],
  },
  {
    id: "corejj",
    name: "CoreJJ",
    realName: "Jo Yong-in",
    region: "LCS",
    role: "Support",
    team: "Team Liquid",
    country: "🇰🇷",
    active: true,
    debutYear: 2014,
    blurb: "A Worlds champion support who became NA's gold standard at the role.",
    achievements: [
      ...rep("worlds_title", [2017], "Samsung"),
      ...rep("regional_title", [2019, 2020, 2025], "Team Liquid"),
      mvp("finals_mvp", 2019, 0.9, "Team Liquid"),
      ...rep("all_pro_1", [2019, 2020, 2021, 2025], "Team Liquid"),
    ],
  },
  {
    id: "blaber",
    name: "Blaber",
    realName: "Robert Huang",
    region: "LCS",
    role: "Jungle",
    team: "Cloud9",
    country: "🇺🇸",
    active: true,
    debutYear: 2018,
    achievements: [
      ...rep("regional_title", [2020, 2021, 2025], "Cloud9"),
      mvp("season_mvp", 2021, 0.82, "Cloud9"),
      mvp("season_mvp", 2022, 0.6, "Cloud9"),
      ...rep("all_pro_1", [2021, 2022, 2025], "Cloud9"),
    ],
  },
  {
    id: "impact",
    name: "Impact",
    realName: "Jung Eon-yeong",
    region: "LCS",
    role: "Top",
    team: "FlyQuest",
    country: "🇰🇷",
    active: true,
    debutYear: 2013,
    blurb: "A 2013 world champion who became one of NA's most durable veterans.",
    achievements: [
      ...rep("worlds_title", [2013], "SKT T1"),
      ...rep("regional_title", [2013, 2025], "SKT / FlyQuest"),
      ...rep("all_pro_1", [2018], "Cloud9"),
      ...rep("all_pro_2", [2020, 2025], "EG / FlyQuest"),
    ],
  },

  // ───────────────── additions: legends & stars ─────────────────
  {
    id: "mata",
    name: "Mata",
    realName: "Cho Se-hyeong",
    region: "LCK",
    role: "Support",
    team: "Samsung (retired)",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    blurb: "First support to win Worlds Finals MVP — the cerebral standard for the role.",
    achievements: [
      ...rep("worlds_title", [2014], "Samsung White"),
      mvp("worlds_mvp", 2014, 1.0, "Samsung White"),
      ...rep("all_pro_1", [2014, 2017], "Samsung / RNG"),
    ],
  },
  {
    id: "madlife",
    name: "MadLife",
    realName: "Hong Min-gi",
    region: "LCK",
    role: "Support",
    team: "CJ Entus (retired)",
    country: "🇰🇷",
    active: false,
    debutYear: 2012,
    blurb: "The support who redefined the role — revered, if title-light.",
    achievements: [
      ...rep("worlds_runnerup", [2012], "Azubu Frost"),
      ...rep("regional_title", [2012], "Azubu Frost"),
      ...rep("all_pro_1", [2012], "Azubu Frost"),
      ...rep("all_pro_2", [2013], "CJ Entus"),
    ],
  },
  {
    id: "bengi",
    name: "Bengi",
    realName: "Bae Seong-ung",
    region: "LCK",
    role: "Jungle",
    team: "SKT (retired)",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    blurb: "Faker's jungler through three world titles.",
    achievements: [
      ...rep("worlds_title", [2013, 2015, 2016], "SKT T1"),
      ...rep("msi_title", [2016], "SKT T1"),
      ...rep("regional_title", [2013, 2015, 2016], "SKT T1"),
      ...rep("worlds_runnerup", [2017], "SKT T1"),
      ...rep("all_pro_1", [2013], "SKT T1"),
      ...rep("all_pro_2", [2015], "SKT T1"),
    ],
  },
  {
    id: "marin",
    name: "MaRin",
    realName: "Jang Gyeong-hwan",
    region: "LCK",
    role: "Top",
    team: "SKT (retired)",
    country: "🇰🇷",
    active: false,
    debutYear: 2014,
    blurb: "2015 Worlds Finals MVP at the peak of SKT's reign.",
    achievements: [
      ...rep("worlds_title", [2015], "SKT T1"),
      mvp("worlds_mvp", 2015, 1.0, "SKT T1"),
      ...rep("regional_title", [2015], "SKT T1"),
      ...rep("all_pro_1", [2015], "SKT T1"),
    ],
  },
  {
    id: "bang",
    name: "Bang",
    realName: "Bae Jun-sik",
    region: "LCK",
    role: "Bot",
    team: "SKT (retired)",
    country: "🇰🇷",
    active: false,
    debutYear: 2014,
    achievements: [
      ...rep("worlds_title", [2015, 2016], "SKT T1"),
      ...rep("msi_title", [2016, 2017], "SKT T1"),
      ...rep("regional_title", [2015, 2016, 2017], "SKT T1"),
      ...rep("worlds_runnerup", [2017], "SKT T1"),
      ...rep("all_pro_1", [2016], "SKT T1"),
      ...rep("all_pro_2", [2015], "SKT T1"),
    ],
  },
  {
    id: "wolf",
    name: "Wolf",
    realName: "Lee Jae-wan",
    region: "LCK",
    role: "Support",
    team: "SKT (retired)",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    achievements: [
      ...rep("worlds_title", [2015, 2016], "SKT T1"),
      ...rep("msi_title", [2016, 2017], "SKT T1"),
      ...rep("regional_title", [2015, 2016, 2017], "SKT T1"),
      ...rep("worlds_runnerup", [2017], "SKT T1"),
      ...rep("all_pro_1", [2016], "SKT T1"),
    ],
  },
  {
    id: "peanut",
    name: "Peanut",
    realName: "Han Wang-ho",
    region: "LCK",
    role: "Jungle",
    team: "Gen.G",
    country: "🇰🇷",
    active: true,
    debutYear: 2015,
    achievements: [
      ...rep("msi_title", [2017], "SKT T1"),
      ...rep("worlds_runnerup", [2017], "SKT T1"),
      ...rep("regional_title", [2017, 2022, 2023, 2024], "SKT / Gen.G"),
      ...rep("all_pro_1", [2022], "Gen.G"),
      ...rep("all_pro_2", [2017], "SKT T1"),
    ],
  },
  {
    id: "khan",
    name: "Khan",
    realName: "Kim Dong-ha",
    region: "LCK",
    role: "Top",
    team: "DWG KIA (retired)",
    country: "🇰🇷",
    active: false,
    debutYear: 2016,
    achievements: [
      mvp("season_mvp", 2018, 0.7, "Kingzone"),
      ...rep("regional_title", [2018, 2019, 2021], "Kingzone / SKT / DWG KIA"),
      ...rep("worlds_runnerup", [2021], "DWG KIA"),
      ...rep("all_pro_1", [2018, 2019], "Kingzone / SKT"),
    ],
  },
  {
    id: "nuguri",
    name: "Nuguri",
    realName: "Jang Ha-gwon",
    region: "LCK",
    role: "Top",
    team: "Dplus KIA",
    country: "🇰🇷",
    active: true,
    debutYear: 2018,
    achievements: [
      ...rep("worlds_title", [2020], "DAMWON"),
      ...rep("regional_title", [2020], "DAMWON"),
      ...rep("worlds_runnerup", [2021], "FunPlus Phoenix"),
      ...rep("all_pro_1", [2020], "DAMWON"),
    ],
  },
  {
    id: "viper",
    name: "Viper",
    realName: "Park Do-hyeon",
    region: "LCK",
    role: "Bot",
    team: "Hanwha Life",
    country: "🇰🇷",
    active: true,
    debutYear: 2020,
    achievements: [
      ...rep("worlds_title", [2021], "EDward Gaming"),
      ...rep("regional_title", [2025], "Hanwha Life"),
      ...rep("all_pro_1", [2023, 2024], "EDG / Hanwha Life"),
    ],
  },
  {
    id: "karsa",
    name: "Karsa",
    realName: "Hung Hao-Hsuan",
    region: "LPL",
    role: "Jungle",
    team: "Top Esports",
    country: "🇹🇼",
    active: true,
    debutYear: 2015,
    achievements: [
      ...rep("msi_title", [2018], "RNG"),
      ...rep("regional_title", [2018, 2021], "RNG / TES"),
      ...rep("all_pro_1", [2018, 2020], "RNG / TES"),
    ],
  },
  {
    id: "ning",
    name: "Ning",
    realName: "Gao Zhen-Ning",
    region: "LPL",
    role: "Jungle",
    team: "Invictus Gaming (retired)",
    country: "🇨🇳",
    active: false,
    debutYear: 2017,
    blurb: "First jungler to win Worlds Finals MVP (2018).",
    achievements: [
      ...rep("worlds_title", [2018], "Invictus Gaming"),
      mvp("worlds_mvp", 2018, 1.0, "Invictus Gaming"),
      ...rep("regional_title", [2019], "IG"),
      ...rep("all_pro_1", [2018], "Invictus Gaming"),
    ],
  },
  {
    id: "crisp",
    name: "Crisp",
    realName: "Liu Qing-Song",
    region: "LPL",
    role: "Support",
    team: "FunPlus Phoenix",
    country: "🇨🇳",
    active: true,
    debutYear: 2018,
    achievements: [
      ...rep("worlds_title", [2019], "FunPlus Phoenix"),
      ...rep("regional_title", [2019], "FPX"),
      ...rep("all_pro_1", [2019], "FPX"),
      ...rep("all_pro_2", [2020], "FPX"),
    ],
  },
  {
    id: "wei",
    name: "Wei",
    realName: "Yan Yang-Wei",
    region: "LPL",
    role: "Jungle",
    team: "Bilibili Gaming",
    country: "🇨🇳",
    active: true,
    debutYear: 2020,
    blurb: "Engine of modern BLG — agonizingly close at 2024 Worlds.",
    achievements: [
      ...rep("regional_title", [2024, 2025], "BLG"),
      ...rep("worlds_runnerup", [2024], "Bilibili Gaming"),
      mvp("season_mvp", 2024, 0.6, "BLG"),
      ...rep("all_pro_1", [2024, 2025], "BLG"),
    ],
  },
  {
    id: "perkz",
    name: "Perkz",
    realName: "Luka Perković",
    region: "LEC",
    role: "Mid",
    team: "G2 Esports",
    country: "🇭🇷",
    active: true,
    debutYear: 2015,
    blurb: "Europe's most decorated — an MSI title and two Worlds finals.",
    achievements: [
      ...rep("msi_title", [2019], "G2 Esports"),
      ...rep("worlds_runnerup", [2019], "G2 Esports"),
      ...rep("regional_title", [2017, 2018, 2019, 2019, 2020], "G2 Esports"),
      mvp("season_mvp", 2017, 0.6, "G2 Esports"),
      ...rep("all_pro_1", [2018, 2019], "G2 Esports"),
    ],
  },
  {
    id: "hylissang",
    name: "Hylissang",
    realName: "Zdravets Galabov",
    region: "LEC",
    role: "Support",
    team: "Fnatic",
    country: "🇧🇬",
    active: true,
    debutYear: 2015,
    achievements: [
      ...rep("regional_title", [2018], "Fnatic"),
      ...rep("worlds_runnerup", [2018], "Fnatic"),
      ...rep("all_pro_1", [2018, 2022], "Fnatic"),
      ...rep("all_pro_2", [2019], "Fnatic"),
    ],
  },
  {
    id: "pray",
    name: "PraY",
    realName: "Kim Jong-in",
    region: "LCK",
    role: "Bot",
    team: "ROX Tigers (retired)",
    country: "🇰🇷",
    active: false,
    debutYear: 2012,
    blurb: "Half of the iconic PraY–GorillA bot lane.",
    achievements: [
      ...rep("worlds_runnerup", [2015], "KOO Tigers"),
      ...rep("regional_runnerup", [2016], "ROX Tigers"),
      ...rep("all_pro_1", [2015, 2016], "ROX Tigers"),
      ...rep("all_pro_2", [2017], "Longzhu"),
    ],
  },
  {
    id: "gorilla",
    name: "GorillA",
    realName: "Kang Beom-hyeon",
    region: "LCK",
    role: "Support",
    team: "ROX Tigers (retired)",
    country: "🇰🇷",
    active: false,
    debutYear: 2013,
    achievements: [
      ...rep("worlds_runnerup", [2015], "KOO Tigers"),
      ...rep("all_pro_1", [2015, 2016], "ROX Tigers"),
    ],
  },
];

// Real honors synced from Leaguepedia (CC BY-SA) by scripts/ingest-leaguepedia.mjs are
// merged onto the curated bios: accurate region/role/team/blurb stay, achievements get
// replaced. Empty file → the curated seed achievements are used as-is.
const GENERATED = generatedAchievements as Record<string, Achievement[]>;

export const PLAYERS: Player[] = CURATED_PLAYERS.map((p) => {
  const synced = GENERATED[p.id];
  return synced && synced.length > 0 ? { ...p, achievements: synced } : p;
});

// ───────────────────────── accessors ─────────────────────────

export function getPlayer(id: string): Player | undefined {
  return PLAYERS.find((p) => p.id === id);
}

export type RankedRow = { player: Player; score: number; rank: number };

export function ranked(
  players: Player[] = PLAYERS,
  w: Weights = DEFAULT_WEIGHTS
): RankedRow[] {
  return players
    .map((player) => ({ player, score: honorScore(player, w) }))
    .sort((a, b) => b.score - a.score)
    .map((row, i) => ({ ...row, rank: i + 1 }));
}

export function filterPlayers(opts: { region?: Region | "ALL"; role?: Role | "ALL" }): Player[] {
  return PLAYERS.filter(
    (p) =>
      (!opts.region || opts.region === "ALL" || p.region === opts.region) &&
      (!opts.role || opts.role === "ALL" || p.role === opts.role)
  );
}

/** Percentile (0..100) of a player's score within a pool. */
export function percentile(player: Player, pool: Player[], w: Weights = DEFAULT_WEIGHTS): number {
  const s = honorScore(player, w);
  const below = pool.filter((p) => honorScore(p, w) < s).length;
  return Math.round((below / Math.max(1, pool.length - 1)) * 100);
}
