// Freely-licensed player portraits. GENERATED by scripts/fetch-photos.mjs from the
// photo-extraction workflow — do not hand-edit; re-run the workflow + script to refresh.
// Every entry is surfaced on /credits for attribution (mostly CC BY / CC BY-SA from
// Wikimedia Commons). Players without a free image fall back to the radiant field.
export type PhotoCredit = {
  /** Public path, e.g. "/players/messi.jpg". */
  src: string;
  /** Photographer / author, as named on Commons. */
  author: string;
  /** Human label, e.g. "CC BY-SA 4.0" or "Public domain". */
  license: string;
  /** Canonical license deed URL (empty for public domain). */
  licenseUrl: string;
  /** Wikimedia Commons file page. */
  source: string;
};

export const PLAYER_PHOTOS: Record<string, PhotoCredit> = {
  "alain-prost": { src: "/players/alain-prost.jpg", author: "Thesupermat", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Festival automobile international 2015 - Photocall - 065 (cropped3).jpg" },
  "ayrton-senna": { src: "/players/ayrton-senna.jpg", author: "Instituto Ayrton Senna", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Ayrton Senna 9 (cropped).jpg" },
  "ceb": { src: "/players/ceb.jpg", author: "artubr", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Dota_2_desk_analysis_-_ESL_One_Frankfurt_2014_%28cropped_to_Ceb%29.jpg" },
  "cho-chikun": { src: "/players/cho-chikun.jpg", author: "Ohtani tanya", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Cho_Chikun_at_World_Go_Festival20190630.jpg" },
  "cristiano-ronaldo": { src: "/players/cristiano-ronaldo.jpg", author: "YantsImages", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Cristiano_Ronaldo_2277.jpg" },
  "deng-yaping": { src: "/players/deng-yaping.jpg", author: "China News Service (中国新闻社)", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:%E9%82%93%E4%BA%9A%E8%90%8D%E5%A5%B3%E5%A3%AB.png" },
  "faker": { src: "/players/faker.jpg", author: "E레기 (Inven)", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Faker_at_2023_MSI_(cropped).jpg" },
  "fan-zhendong": { src: "/players/fan-zhendong.jpg", author: "XIAOYU TANG", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", source: "https://commons.wikimedia.org/wiki/File:Fan_Zhendong_ACTTC2016_8.jpeg" },
  "gu-li": { src: "/players/gu-li.jpg", author: "China News Service (中国新闻社)", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Gu_Li_2024.jpg" },
  "gumayusi": { src: "/players/gumayusi.jpg", author: "fomos esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Gumayusi,_2023_worlds_winning_team_interview.jpg" },
  "jackie-stewart": { src: "/players/jackie-stewart.jpg", author: "Lothar Spurzem", license: "CC BY-SA 2.0 DE", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/de/deed.en", source: "https://commons.wikimedia.org/wiki/File:Stewart, Jackie (Foto Spurzem 1973).jpg" },
  "juan-manuel-fangio": { src: "/players/juan-manuel-fangio.jpg", author: "Bjørn Fjørtoft / Arkivverket (Norwegian National Archives)", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Fangio in 1955 (cropped).jpg" },
  "kareem-abdul-jabbar": { src: "/players/kareem-abdul-jabbar.jpg", author: "Yahoo", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Kareem Abdul-Jabbar at Pre-White House Correspondents' Dinner Reception Pre-Party - 14090760686.jpg" },
  "kobe-bryant": { src: "/players/kobe-bryant.jpg", author: "Keith Allison from Hanover, MD, USA", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", source: "https://commons.wikimedia.org/wiki/File:Kobe Bryant 2015.jpg" },
  "larry-bird": { src: "/players/larry-bird.jpg", author: "Steve Lipofsky (www.Basketballphoto.com)", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", source: "https://commons.wikimedia.org/wiki/File:Larry Bird Lipofsky (high quality).jpg" },
  "lebron-james": { src: "/players/lebron-james.jpg", author: "Erik Drost", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:LeBron_James_(51915470845).jpg" },
  "lee-sedol": { src: "/players/lee-sedol.jpg", author: "LG Electronics", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Lee_Se-Dol_-_2016_%28cropped%29.jpg" },
  "li-xiaoxia": { src: "/players/li-xiaoxia.jpg", author: "Pierre-Yves Beaudouin", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", source: "https://commons.wikimedia.org/wiki/File:Mondial_Ping_-_Women%27s_Singles_-_Final_-_Li_Xiaoxia.jpg" },
  "liu-shiwen": { src: "/players/liu-shiwen.jpg", author: "Xiaoyu Tang", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", source: "https://commons.wikimedia.org/wiki/File:Liu_Shiwen_ACTTC2016_4.jpeg" },
  "ma-long": { src: "/players/ma-long.jpg", author: "Xiaoyu Tang", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", source: "https://commons.wikimedia.org/wiki/File:Ma Long WTTC2016 12.jpeg" },
  "magic-johnson": { src: "/players/magic-johnson.jpg", author: "Steve Lipofsky", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", source: "https://commons.wikimedia.org/wiki/File:Magic_Johnson_Steve_Lipofsky.jpg" },
  "max-verstappen": { src: "/players/max-verstappen.jpg", author: "Steffen Prößdorf", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:2024-08-25_Motorsport,_Formel_1,_Großer_Preis_der_Niederlande_2024_STP_3973_by_Stepro.jpg" },
  "messi": { src: "/players/messi.jpg", author: "Bryan Berlin", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Lionel_Messi_NE_Revolution_Inter_Miami_7.9.25-178_(cropped_2).jpg" },
  "michael-jordan": { src: "/players/michael-jordan.jpg", author: "DOD photo by D. Myles Cullen", license: "Public domain", licenseUrl: "", source: "https://commons.wikimedia.org/wiki/File:Michael_Jordan_in_2014.jpg" },
  "michael-schumacher": { src: "/players/michael-schumacher.jpg", author: "Andrew Griffith (2012 Chinese Grand Prix)", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Schumacher china 2012 crop.jpg" },
  "modric": { src: "/players/modric.jpg", author: "Светлана Бекетова", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", source: "https://commons.wikimedia.org/wiki/File:Luka_Modrić_in_2018.jpg" },
  "nelson-piquet": { src: "/players/nelson-piquet.jpg", author: "Agência Brasília", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Cerimonia de entrega da medalha Brasília 60 anos - 16.jpg" },
  "niki-lauda": { src: "/players/niki-lauda.jpg", author: "Hans van Dijk for Anefo / Dutch National Archives", license: "CC0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/", source: "https://commons.wikimedia.org/wiki/File:Lauda at 1982 Dutch Grand Prix.jpg" },
  "park-junghwan": { src: "/players/park-junghwan.jpg", author: "Cheongju MBC (official Youtube account)", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:(청주MBC뉴스)_청남대_바둑전쟁_박정환_9단_웃다.jpg" },
  "pele": { src: "/players/pele.jpg", author: "Anefo (Dutch National Archives)", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", source: "https://commons.wikimedia.org/wiki/File:Pele_(voetballer)_(kop),_Bestanddeelnr_918-6208.jpg" },
  "puppey": { src: "/players/puppey.jpg", author: "ybbuc", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Puppey_at_The_International_2014.jpg" },
  "ruler": { src: "/players/ruler.jpg", author: "fomos esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:GEN_Ruler_2022.jpg" },
  "sergio-ramos": { src: "/players/sergio-ramos.jpg", author: "Ruben Ortega", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Sergio_Ramos_entrenando_(cropped).jpg" },
  "shaquille-oneal": { src: "/players/shaquille-oneal.jpg", author: "TechCrunch", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:TechCrunch_Disrupt_2023_-_Day_1_(cropped).jpg" },
  "tenz": { src: "/players/tenz.jpg", author: "Billgatenguyen", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:SEN_TENZ_2023.jpg" },
  "tim-duncan": { src: "/players/tim-duncan.jpg", author: "Keith Allison from Owings Mills, USA", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", source: "https://commons.wikimedia.org/wiki/File:Tim Duncan.jpg" },
  "toni-kroos": { src: "/players/toni-kroos.jpg", author: "Michael Kranewitter", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", source: "https://commons.wikimedia.org/wiki/File:FIFA_WC-qualification_2014_-_Austria_vs._Germany_2012-09-11_-_Toni_Kroos.JPG" },
  "wang-nan": { src: "/players/wang-nan.jpg", author: "Michel (flickr.com/photos/mfi)", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Wangnan_2001.jpg" },
  "wilt-chamberlain": { src: "/players/wilt-chamberlain.jpg", author: "Fred Palumbo", license: "Public domain", licenseUrl: "", source: "https://commons.wikimedia.org/wiki/File:Wilt Chamberlain (restored).jpg" },
  "xavi": { src: "/players/xavi.jpg", author: "Doha Stadium Plus Qatar (Mohan)", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Xavi_Hernandez_(18090182763).jpg" },
  "zeus": { src: "/players/zeus.jpg", author: "Fomos Esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Zeus,_2023_worlds_winning_team_interview.jpg" },
  "keria": { src: "/players/keria.jpg", author: "fomos esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Keria,_2023_worlds_winning_team_interview.jpg" },
  "oner": { src: "/players/oner.jpg", author: "Fomos Esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Oner_in_2024.jpg" },
  "bang": { src: "/players/bang.jpg", author: "fomos esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:%EB%B1%85_%EB%B0%B0%EC%A4%80%EC%8B%9D.jpg" },
  "collapse": { src: "/players/collapse.jpg", author: "Youtube: Paragon Events Dota 2", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Collapse_PGL_Wallachia_Season_1.png" },
  "lewis-hamilton": { src: "/players/lewis-hamilton.jpg", author: "Jen Ross (Jen_ross83)", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Lewis_Hamilton_Silverstone_2018_(cropped).jpg" },
  "demon1": { src: "/players/demon1.jpg", author: "Kayorichi", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", source: "https://commons.wikimedia.org/wiki/File:EnKay_53144374843_c77d1cc0a5_k_1693122682132.jpg" },
  "uzi": { src: "/players/uzi.jpg", author: "Bruce Liu", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", source: "https://commons.wikimedia.org/wiki/File:500px_photo_(117688341).jpeg" },
  "ronaldo-r9": { src: "/players/ronaldo-r9.jpg", author: "Stephen McCarthy / Web Summit via Sportsfile", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Ronaldo_Lu%C3%ADs_Naz%C3%A1rio_de_Lima_2019_(3x4_cropped).jpg" },
  "gerd-muller": { src: "/players/gerd-muller.jpg", author: "Alexander Hauk (Promifotos.de / www.alexander-hauk.de)", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/", source: "https://commons.wikimedia.org/wiki/File:BOMBERGERDMUELLER_(headshot).JPG" },
  "iniesta": { src: "/players/iniesta.jpg", author: "首相官邸 (Prime Minister's Office of Japan)", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", source: "https://commons.wikimedia.org/wiki/File:Andr%C3%A9s_Iniesta_2019.jpg" },
  "karim-benzema": { src: "/players/karim-benzema.jpg", author: "Real Madrid CF", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Karim_Benzema_2021.jpg" },
  "beckenbauer": { src: "/players/beckenbauer.jpg", author: "Immanuel Giel (cropped by afrank99)", license: "Public domain (released worldwide by author)", licenseUrl: "https://commons.wikimedia.org/wiki/File:Franz_Beckenbauer_2006_06_17.jpg", source: "https://commons.wikimedia.org/wiki/File:Franz_Beckenbauer_2006_06_17.jpg" },
  "cruyff": { src: "/players/cruyff.jpg", author: "Rob Mieremet / Anefo (Nationaal Archief)", license: "CC0 1.0 (Public Domain Dedication)", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en", source: "https://commons.wikimedia.org/wiki/File:Johan_Cruyff_1974c.jpg" },
  "di-stefano": { src: "/players/di-stefano.jpg", author: "Wim van Rossem / Anefo (Dutch National Archives)", license: "CC0 1.0 (Public Domain Dedication)", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en", source: "https://commons.wikimedia.org/wiki/File:Di_Stefano_1959.jpg" },
  "sergio-busquets": { src: "/players/sergio-busquets.jpg", author: "Bryan Berlin (User:Berlination)", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", source: "https://commons.wikimedia.org/wiki/File:Sergio_Busquets_NYCFC_Miami_24_Sep_2025-020_(cropped).jpg" },
  "van-basten": { src: "/players/van-basten.jpg", author: "Paul Blank (postproduktie.nl)", license: "CC BY 2.5", licenseUrl: "https://creativecommons.org/licenses/by/2.5/", source: "https://commons.wikimedia.org/wiki/File:Marco_van_Basten_(2).jpg" },
  "casillas": { src: "/players/casillas.jpg", author: "Sam Barnes / Web Summit / Sportsfile", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", source: "https://commons.wikimedia.org/wiki/File:Iker-Casillas-SportsTrade-2021-cropped.jpg" },
  "roberto-carlos": { src: "/players/roberto-carlos.jpg", author: "Lukas Schulze / Sportsfile for Web Summit", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", source: "https://commons.wikimedia.org/wiki/File:LS3_1288_(53332367864)_(cropped).jpg" },
  "zidane": { src: "/players/zidane.jpg", author: "Hadi Abyar (Tasnim News Agency)", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Zinedine_Zidane_by_Tasnim_03.jpg" },
};

export function playerPhoto(id: string): PhotoCredit | undefined {
  return PLAYER_PHOTOS[id];
}
