// Freely-licensed player portraits. GENERATED by scripts/fetch-photos.mjs from the
// photo-extraction workflow — do not hand-edit; re-run the workflow + script to refresh.
// Every entry is surfaced on /credits for attribution (mostly CC BY / CC BY-SA from
// Wikimedia Commons). Players without a free image fall back to the radiant field.
export type PhotoCredit = {
  /** Public path, e.g. "/players/messi.jpg". */
  src: string;
  /** Photographer / author, as named on Commons. */
  author: string;
  /** Human label, e.g. "CC BY-SA 4.0" or "Public domain". */
  license: string;
  /** Canonical license deed URL (empty for public domain). */
  licenseUrl: string;
  /** Wikimedia Commons file page. */
  source: string;
};

export const PLAYER_PHOTOS: Record<string, PhotoCredit> = {
  "alain-prost": { src: "/players/alain-prost.jpg", author: "Thesupermat", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Festival_automobile_international_2015_-_Photocall_-_065_(cropped3).jpg" },
  "ayrton-senna": { src: "/players/ayrton-senna.jpg", author: "Instituto Ayrton Senna", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Ayrton_Senna_9_(cropped).jpg" },
  "ceb": { src: "/players/ceb.jpg", author: "artubr", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Dota_2_desk_analysis_-_ESL_One_Frankfurt_2014_%28cropped_to_Ceb%29.jpg" },
  "cho-chikun": { src: "/players/cho-chikun.jpg", author: "Ohtani tanya", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Cho_Chikun_at_World_Go_Festival20190630.jpg" },
  "cho-hunhyun": { src: "/players/cho-hunhyun.jpg", author: "Kadeem (Turkish Wikipedia)", license: "CC BY-SA 3.0", licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/", source: "https://commons.wikimedia.org/wiki/File:Chohunhyun1.jpg" },
  "cristiano-ronaldo": { src: "/players/cristiano-ronaldo.jpg", author: "YantsImages", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Cristiano_Ronaldo_2275_(cropped).jpg" },
  "deng-yaping": { src: "/players/deng-yaping.jpg", author: "中国新闻社 (China News Service)", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:邓亚萍女士.png" },
  "faker": { src: "/players/faker.jpg", author: "fomos esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Faker,_2023_Worlds_winning_team_interview.jpg" },
  "fan-zhendong": { src: "/players/fan-zhendong.jpg", author: "Peter Porai-Koshits", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:ITTF_World_Tour_2017_German_Open_Fan_Zhendong_03.jpg" },
  "gerd-muller": { src: "/players/gerd-muller.jpg", author: "Unknown author", license: "Public domain", licenseUrl: "", source: "https://commons.wikimedia.org/wiki/File:Gerd_Müller_c1973_(cropped).jpg" },
  "gu-li": { src: "/players/gu-li.jpg", author: "China News Service (中国新闻社)", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Gu_Li_2024.jpg" },
  "gumayusi": { src: "/players/gumayusi.jpg", author: "Fomos Esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Gumayusi_in_2021_interview.jpg" },
  "iniesta": { src: "/players/iniesta.jpg", author: "内閣官房内閣広報室 (Cabinet Public Relations Office)", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Andrés_Iniesta_2019.jpg" },
  "jackie-stewart": { src: "/players/jackie-stewart.jpg", author: "David Merrett from Daventry, England", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Jackie_Stewart_at_the_2014_WEC_Silverstone_round.jpg" },
  "juan-manuel-fangio": { src: "/players/juan-manuel-fangio.jpg", author: "Bjørn Fjørtoft", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Fangio_in_1955_(cropped).jpg" },
  "kareem-abdul-jabbar": { src: "/players/kareem-abdul-jabbar.jpg", author: "Yahoo", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Kareem Abdul-Jabbar at Pre-White House Correspondents' Dinner Reception Pre-Party - 14090760686.jpg" },
  "kobe-bryant": { src: "/players/kobe-bryant.jpg", author: "Keith Allison from Hanover, MD, USA", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", source: "https://commons.wikimedia.org/wiki/File:Kobe Bryant 2015.jpg" },
  "larry-bird": { src: "/players/larry-bird.jpg", author: "Kurt Shimala", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", source: "https://commons.wikimedia.org/wiki/File:Larrybird.jpg" },
  "lebron-james": { src: "/players/lebron-james.jpg", author: "Erik Drost", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:LeBron James with Cleveland 2018.jpeg" },
  "lee-chang-ho": { src: "/players/lee-chang-ho.jpg", author: "chevy0193", license: "Public domain", licenseUrl: "https://en.wikipedia.org/wiki/Public_domain", source: "https://commons.wikimedia.org/wiki/File:Lee_ChangHo.JPG" },
  "lee-sedol": { src: "/players/lee-sedol.jpg", author: "LG Electronics", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Lee_Se-Dol_-_2016_(cropped).jpg" },
  "li-xiaoxia": { src: "/players/li-xiaoxia.jpg", author: "Pierre-Yves Beaudouin", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", source: "https://commons.wikimedia.org/wiki/File:Mondial_Ping_-_Women's_Singles_-_Final_-_Li_Xiaoxia.jpg" },
  "liu-shiwen": { src: "/players/liu-shiwen.jpg", author: "Pierre-Yves Beaudouin", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Mondial_Ping_-_Women's_Doubles_-_Final_-_10.jpg" },
  "ma-long": { src: "/players/ma-long.jpg", author: "XIAOYU TANG", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", source: "https://commons.wikimedia.org/wiki/File:Ma_Long_ATTC2017_29.jpeg" },
  "magic-johnson": { src: "/players/magic-johnson.jpg", author: "Daniel Benavides from Austin, TX", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Magic Johnson at SXSW 2022 (51958597733).jpg" },
  "max-verstappen": { src: "/players/max-verstappen.jpg", author: "Steffen Prösdorf", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:2024-08-25_Motorsport,_Formel_1,_Großer_Preis_der_Niederlande_2024_STP_3973_by_Stepro_(medium_crop).jpg" },
  "messi": { src: "/players/messi.jpg", author: "Bryan Berlin", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Lionel_Messi_NE_Revolution_Inter_Miami_7.9.25-178_(cropped_2).jpg" },
  "michael-jordan": { src: "/players/michael-jordan.jpg", author: "DOD photo by D. Myles Cullen", license: "Public domain", licenseUrl: "", source: "https://commons.wikimedia.org/wiki/File:Michael_Jordan_in_2014.jpg" },
  "michael-schumacher": { src: "/players/michael-schumacher.jpg", author: "Original: Aécio Neves – Wellington Pedro/Imprensa MG; Derivative work: F1fans, FMSky", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Aécio_Neves,_Michael_Schumacher_e_Didi_(Cropped).jpg" },
  "modric": { src: "/players/modric.jpg", author: "Fotografías Archimadrid.es", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Ofrenda_de_la_Liga_y_la_Champions-57-L.Millán_(52109310843)_(Luka_Modrić).jpg" },
  "nelson-piquet": { src: "/players/nelson-piquet.jpg", author: "Agência Brasília", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Cerimonia_de_entrega_da_medalha_Brasília_60_anos_-_16.jpg" },
  "niki-lauda": { src: "/players/niki-lauda.jpg", author: "Hans van Dijk for Anefo", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", source: "https://commons.wikimedia.org/wiki/File:Lauda_at_1982_Dutch_Grand_Prix.jpg" },
  "park-junghwan": { src: "/players/park-junghwan.jpg", author: "Cheongju MBC (official Youtube account)", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:(청주MBC뉴스)_청남대_바둑전쟁_박정환_9단_웃다.jpg" },
  "pele": { src: "/players/pele.jpg", author: "Unknown author", license: "Public domain", licenseUrl: "", source: "https://commons.wikimedia.org/wiki/File:Pele_con_brasil_(cropped).jpg" },
  "puppey": { src: "/players/puppey.jpg", author: "ybbuc", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Puppey_at_The_International_2014.jpg" },
  "ronaldo-r9": { src: "/players/ronaldo-r9.jpg", author: "Web Summit", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Ronaldo_Luís_Nazário_de_Lima_2019_(3x4_cropped).jpg" },
  "ruler": { src: "/players/ruler.jpg", author: "Fomos Esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Ruler_2020_LCK_Photoshoot.jpg" },
  "sebastian-vettel": { src: "/players/sebastian-vettel.jpg", author: "Sven Mandel", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Sebastian_Vettel_-_2022236172324_2022-08-24_Champions_for_Charity_-_Sven_-_1D_X_MK_II_-_0418_-_B70I2428_(cropped).jpg" },
  "sergio-ramos": { src: "/players/sergio-ramos.jpg", author: "Real Madrid", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Sergio_Ramos_Interview_2021_(cropped).jpg" },
  "shaquille-oneal": { src: "/players/shaquille-oneal.jpg", author: "TechCrunch", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:TechCrunch_Disrupt_2023_-_Day_1_(cropped).jpg" },
  "tenz": { src: "/players/tenz.jpg", author: "Billgatenguyen", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:SEN_TENZ_2023.jpg" },
  "tim-duncan": { src: "/players/tim-duncan.jpg", author: "Keith Allison from Owings Mills, USA", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", source: "https://commons.wikimedia.org/wiki/File:Tim Duncan.jpg" },
  "toni-kroos": { src: "/players/toni-kroos.jpg", author: "Real Madrid (youtube.com/@realmadrid)", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Toni_Kroos_Real_Madrid_2021.jpg" },
  "wang-nan": { src: "/players/wang-nan.jpg", author: "MIchel", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", source: "https://commons.wikimedia.org/wiki/File:Wangnan_2001.jpg" },
  "wilt-chamberlain": { src: "/players/wilt-chamberlain.jpg", author: "Fred Palumbo", license: "Public domain", licenseUrl: "", source: "https://commons.wikimedia.org/wiki/File:Wilt Chamberlain (restored).jpg" },
  "xavi": { src: "/players/xavi.jpg", author: "Meysam Mehabadi", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", source: "https://commons.wikimedia.org/wiki/File:Xavi,_Persepolis_vs._Al_Sadd,_20190520_02_(cropped).jpg" },
  "yoo-changhyuk": { src: "/players/yoo-changhyuk.jpg", author: "Leedors527, derivative work by Veinarde", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", source: "https://commons.wikimedia.org/wiki/File:Yoo_Changhyuk_cropped.jpg" },
  "zeus": { src: "/players/zeus.jpg", author: "Fomos Esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Zeus_2024_post-match_interview.jpg" },
  "zhang-jike": { src: "/players/zhang-jike.jpg", author: "Pierre-Yves Beaudouin", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", source: "https://commons.wikimedia.org/wiki/File:Mondial_Ping_-_Men's_Singles_-_Final_-_Zhang_Jike_vs_Wang_Hao_-_40.jpg" },
  "keria": { src: "/players/keria.jpg", author: "E레기", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Keria_2020_interview.jpg" },
  "oner": { src: "/players/oner.jpg", author: "Fomos Esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Oner_in_2024.jpg" },
  "bang": { src: "/players/bang.jpg", author: "fomos esports", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:%EB%B1%85_%EB%B0%B0%EC%A4%80%EC%8B%9D.jpg" },
  "collapse": { src: "/players/collapse.jpg", author: "Youtube: Paragon Events Dota 2", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0", source: "https://commons.wikimedia.org/wiki/File:Collapse_PGL_Wallachia_Season_1.png" },
};

export function playerPhoto(id: string): PhotoCredit | undefined {
  return PLAYER_PHOTOS[id];
}
