import type { Achievement, Player } from "../types";

/**
 * Initial football roster — the consensus all-time greats across eras, positions
 * and leagues, with their well-established headline honors. This is a seed set to
 * be expanded and re-verified (league-title year lists especially); high-confidence
 * items (Ballon d'Or, World Cup, Champions League, Euro/Copa years) are prioritized.
 */

// Compact achievement builder: one entry per year for a given type.
const T = (type: string, years: number[], team?: string): Achievement[] =>
  years.map((year) => (team ? { type, year, team } : { type, year }));

export const FOOTBALL_PLAYERS: Player[] = [
  {
    id: "messi", name: "Lionel Messi", realName: "Lionel Andrés Messi", sport: "football",
    league: "LALIGA", position: "FWD", team: "Barcelona", nation: "Argentina", active: true, debutYear: 2004,
    blurb: "Eight Ballon d'Ors and, finally, the World Cup — the most decorated player in the game's history.",
    achievements: [
      ...T("ballon_dor", [2009, 2010, 2011, 2012, 2015, 2019, 2021, 2023]),
      ...T("fifa_best", [2019, 2022, 2023]),
      ...T("golden_shoe", [2010, 2012, 2013, 2017, 2018, 2019]),
      ...T("wc_golden_ball", [2014, 2022]),
      ...T("world_cup", [2022]),
      ...T("wc_runnerup", [2014]),
      ...T("continental_nt", [2021, 2024]),
      ...T("olympic_gold_u23", [2008]),
      ...T("champions_league", [2006, 2009, 2011, 2015], "Barcelona"),
      ...T("league_title", [2005, 2006, 2009, 2010, 2011, 2013, 2015, 2016, 2018, 2019], "Barcelona"),
      ...T("league_title", [2022, 2023], "Paris Saint-Germain"),
      ...T("club_world_cup", [2009, 2011, 2015], "Barcelona"),
      ...T("domestic_cup", [2009, 2012, 2015, 2016, 2017, 2018, 2021], "Barcelona"),
    ],
  },
  {
    id: "cristiano-ronaldo", name: "Cristiano Ronaldo", realName: "Cristiano Ronaldo dos Santos Aveiro", sport: "football",
    league: "LALIGA", position: "FWD", team: "Real Madrid", nation: "Portugal", active: true, debutYear: 2002,
    blurb: "Five Ballon d'Ors and a record five Champions Leagues across England, Spain and Italy.",
    achievements: [
      ...T("ballon_dor", [2008, 2013, 2014, 2016, 2017]),
      ...T("fifa_best", [2008, 2016, 2017]),
      ...T("golden_shoe", [2008, 2011, 2014, 2015]),
      ...T("continental_nt", [2016]),
      ...T("nations_league", [2019, 2025]),
      ...T("continental_nt_runnerup", [2004]),
      ...T("champions_league", [2008], "Manchester United"),
      ...T("champions_league", [2014, 2016, 2017, 2018], "Real Madrid"),
      ...T("league_title", [2007, 2008, 2009], "Manchester United"),
      ...T("league_title", [2012, 2017], "Real Madrid"),
      ...T("league_title", [2019, 2020], "Juventus"),
      ...T("club_world_cup", [2008], "Manchester United"),
      ...T("club_world_cup", [2014, 2016, 2017], "Real Madrid"),
      ...T("ballon_dor_2nd", [2009, 2018]),
    ],
  },
  {
    id: "pele", name: "Pelé", realName: "Edson Arantes do Nascimento", sport: "football",
    league: "SOUTHAM", position: "FWD", team: "Santos", nation: "Brazil", active: false, debutYear: 1956,
    blurb: "The only player to win three World Cups; ineligible for the Ballon d'Or of his era (retroactively credited).",
    achievements: [
      ...T("world_cup", [1958, 1962, 1970]),
      ...T("wc_golden_ball", [1970]),
      ...T("ballon_dor_retro", [1958, 1959, 1960, 1961, 1963, 1964, 1970]),
      ...T("copa_libertadores", [1962, 1963], "Santos"),
      ...T("club_world_cup", [1962, 1963], "Santos"),
      ...T("league_title", [1961, 1962, 1963, 1964, 1965], "Santos"),
    ],
  },
  {
    id: "maradona", name: "Diego Maradona", realName: "Diego Armando Maradona", sport: "football",
    league: "SERIEA", position: "FWD", team: "Napoli", nation: "Argentina", active: false, debutYear: 1976,
    blurb: "Dragged Argentina to the 1986 World Cup and lifted Napoli to its only Scudetti — peak genius over volume.",
    achievements: [
      ...T("world_cup", [1986]),
      ...T("wc_runnerup", [1990]),
      ...T("wc_golden_ball", [1986]),
      ...T("ballon_dor_retro", [1986, 1990]),
      ...T("league_title", [1987, 1990], "Napoli"),
      ...T("europa_league", [1989], "Napoli"),
      ...T("domestic_cup", [1987], "Napoli"),
    ],
  },
  {
    id: "di-stefano", name: "Alfredo Di Stéfano", realName: "Alfredo Di Stéfano Laulhé", sport: "football",
    league: "LALIGA", position: "FWD", team: "Real Madrid", nation: "Argentina", active: false, debutYear: 1945,
    blurb: "Engine of Real Madrid's five straight European Cups (1956–60).",
    achievements: [
      ...T("ballon_dor", [1957, 1959]),
      ...T("champions_league", [1956, 1957, 1958, 1959, 1960], "Real Madrid"),
      ...T("league_title", [1954, 1955, 1957, 1958, 1961, 1962, 1963, 1964], "Real Madrid"),
      ...T("club_world_cup", [1960], "Real Madrid"),
    ],
  },
  {
    id: "cruyff", name: "Johan Cruyff", realName: "Hendrik Johannes Cruijff", sport: "football",
    league: "EREDIVISIE", position: "FWD", team: "Ajax", nation: "Netherlands", active: false, debutYear: 1964,
    blurb: "Total Football's avatar — three Ballon d'Ors and three straight European Cups with Ajax.",
    alsoId: "cruyff-coach",
    achievements: [
      ...T("ballon_dor", [1971, 1973, 1974]),
      ...T("champions_league", [1971, 1972, 1973], "Ajax"),
      ...T("wc_runnerup", [1974]),
      ...T("league_title", [1966, 1967, 1968, 1970, 1972, 1973, 1982, 1983], "Ajax"),
      ...T("league_title", [1974], "Barcelona"),
      ...T("club_world_cup", [1972], "Ajax"),
    ],
  },
  {
    id: "beckenbauer", name: "Franz Beckenbauer", realName: "Franz Anton Beckenbauer", sport: "football",
    league: "BUNDESLIGA", position: "DEF", team: "Bayern Munich", nation: "Germany", active: false, debutYear: 1964,
    blurb: "Der Kaiser — reinvented the libero role; World Cup winner as player and manager.",
    alsoId: "beckenbauer-coach",
    achievements: [
      ...T("ballon_dor", [1972, 1976]),
      ...T("world_cup", [1974]),
      ...T("wc_runnerup", [1966]),
      ...T("continental_nt", [1972]),
      ...T("champions_league", [1974, 1975, 1976], "Bayern Munich"),
      ...T("league_title", [1969, 1972, 1973, 1974], "Bayern Munich"),
      ...T("club_world_cup", [1976], "Bayern Munich"),
    ],
  },
  {
    id: "ronaldo-r9", name: "Ronaldo Nazário", realName: "Ronaldo Luís Nazário de Lima", sport: "football",
    league: "SERIEA", position: "FWD", team: "Inter Milan", nation: "Brazil", active: false, debutYear: 1993,
    blurb: "O Fenômeno — two World Cups and two Ballon d'Ors despite career-altering knee injuries.",
    achievements: [
      ...T("ballon_dor", [1997, 2002]),
      ...T("fifa_best", [1996, 1997, 2002]),
      ...T("world_cup", [1994, 2002]),
      ...T("wc_runnerup", [1998]),
      ...T("wc_golden_ball", [1998]),
      ...T("wc_golden_boot", [2002]),
      ...T("continental_nt", [1997, 1999]),
      ...T("league_title", [2003], "Real Madrid"),
      ...T("europa_league", [1998], "Inter Milan"),
    ],
  },
  {
    id: "zidane", name: "Zinedine Zidane", realName: "Zinédine Yazid Zidane", sport: "football",
    league: "LALIGA", position: "MID", team: "Real Madrid", nation: "France", active: false, debutYear: 1989,
    blurb: "World Cup, Euro and a volley for the ages in the 2002 Champions League final.",
    alsoId: "zidane-coach",
    achievements: [
      ...T("ballon_dor", [1998]),
      ...T("fifa_best", [1998, 2000, 2003]),
      ...T("world_cup", [1998]),
      ...T("continental_nt", [2000]),
      ...T("wc_runnerup", [2006]),
      ...T("wc_golden_ball", [2006]),
      ...T("champions_league", [2002], "Real Madrid"),
      ...T("league_title", [1997, 1998], "Juventus"),
      ...T("league_title", [2003], "Real Madrid"),
      ...T("club_world_cup", [2002], "Real Madrid"),
    ],
  },
  {
    id: "ronaldinho", name: "Ronaldinho", realName: "Ronaldo de Assis Moreira", sport: "football",
    league: "LALIGA", position: "FWD", team: "Barcelona", nation: "Brazil", active: false, debutYear: 1998,
    blurb: "Joy made football — a Ballon d'Or, a World Cup and a Champions League at Barcelona's rebirth.",
    achievements: [
      ...T("ballon_dor", [2005]),
      ...T("fifa_best", [2004, 2005]),
      ...T("world_cup", [2002]),
      ...T("continental_nt", [1999]),
      ...T("confederations_cup", [2005]),
      ...T("champions_league", [2006], "Barcelona"),
      ...T("league_title", [2005, 2006], "Barcelona"),
      ...T("copa_libertadores", [2013], "Atlético Mineiro"),
    ],
  },
  {
    id: "van-basten", name: "Marco van Basten", realName: "Marcel van Basten", sport: "football",
    league: "SERIEA", position: "FWD", team: "AC Milan", nation: "Netherlands", active: false, debutYear: 1981,
    blurb: "Three Ballon d'Ors and an impossible volley to win Euro 1988, before injury cut him short.",
    achievements: [
      ...T("ballon_dor", [1988, 1989, 1992]),
      ...T("fifa_best", [1992]),
      ...T("continental_nt", [1988]),
      ...T("champions_league", [1989, 1990], "AC Milan"),
      ...T("league_title", [1982, 1983, 1985], "Ajax"),
      ...T("league_title", [1988, 1992, 1993, 1994], "AC Milan"),
      ...T("club_world_cup", [1989, 1990], "AC Milan"),
    ],
  },
  {
    id: "platini", name: "Michel Platini", realName: "Michel François Platini", sport: "football",
    league: "SERIEA", position: "MID", team: "Juventus", nation: "France", active: false, debutYear: 1972,
    blurb: "Three consecutive Ballon d'Ors and the talisman of France's Euro 1984 triumph.",
    achievements: [
      ...T("ballon_dor", [1983, 1984, 1985]),
      ...T("continental_nt", [1984]),
      ...T("champions_league", [1985], "Juventus"),
      ...T("league_title", [1984, 1986], "Juventus"),
      ...T("club_world_cup", [1985], "Juventus"),
    ],
  },
  {
    id: "xavi", name: "Xavi Hernández", realName: "Xavier Hernández Creus", sport: "football",
    league: "LALIGA", position: "MID", team: "Barcelona", nation: "Spain", active: false, debutYear: 1998,
    blurb: "The metronome of Spain's and Barcelona's golden age — a World Cup, two Euros, four Champions Leagues.",
    achievements: [
      ...T("world_cup", [2010]),
      ...T("continental_nt", [2008, 2012]),
      ...T("champions_league", [2006, 2009, 2011, 2015], "Barcelona"),
      ...T("league_title", [2005, 2006, 2009, 2010, 2011, 2013, 2015, 2016], "Barcelona"),
      ...T("club_world_cup", [2009, 2011, 2015], "Barcelona"),
      ...T("ballon_dor_3rd", [2009, 2010, 2011]),
    ],
  },
  {
    id: "iniesta", name: "Andrés Iniesta", realName: "Andrés Iniesta Luján", sport: "football",
    league: "LALIGA", position: "MID", team: "Barcelona", nation: "Spain", active: false, debutYear: 2002,
    blurb: "Scored the goal that won Spain the World Cup; the most graceful midfielder of his generation.",
    achievements: [
      ...T("world_cup", [2010]),
      ...T("continental_nt", [2008, 2012]),
      ...T("champions_league", [2006, 2009, 2011, 2015], "Barcelona"),
      ...T("league_title", [2005, 2006, 2009, 2010, 2011, 2013, 2015, 2016, 2018], "Barcelona"),
      ...T("club_world_cup", [2009, 2011, 2015], "Barcelona"),
      ...T("ballon_dor_3rd", [2010, 2012]),
    ],
  },
  {
    id: "modric", name: "Luka Modrić", realName: "Luka Modrić", sport: "football",
    league: "LALIGA", position: "MID", team: "Real Madrid", nation: "Croatia", active: true, debutYear: 2003,
    blurb: "Broke the Messi–Ronaldo Ballon d'Or duopoly in 2018; six Champions Leagues with Real Madrid.",
    achievements: [
      ...T("ballon_dor", [2018]),
      ...T("fifa_best", [2018]),
      ...T("uefa_poty", [2018]),
      ...T("wc_golden_ball", [2018]),
      ...T("wc_runnerup", [2018]),
      ...T("champions_league", [2014, 2016, 2017, 2018, 2022, 2024], "Real Madrid"),
      ...T("league_title", [2017, 2020, 2022, 2024], "Real Madrid"),
      ...T("club_world_cup", [2014, 2016, 2017, 2018, 2022], "Real Madrid"),
    ],
  },
  {
    id: "maldini", name: "Paolo Maldini", realName: "Paolo Cesare Maldini", sport: "football",
    league: "SERIEA", position: "DEF", team: "AC Milan", nation: "Italy", active: false, debutYear: 1985,
    blurb: "Twenty-five years at Milan, five European Cups — the gold standard at left-back and centre-back.",
    achievements: [
      ...T("champions_league", [1989, 1990, 1994, 2003, 2007], "AC Milan"),
      ...T("league_title", [1988, 1992, 1993, 1994, 1996, 1999, 2004], "AC Milan"),
      ...T("wc_runnerup", [1994]),
      ...T("continental_nt_runnerup", [2000]),
      ...T("club_world_cup", [1989, 1990, 2007], "AC Milan"),
    ],
  },
  {
    id: "cannavaro", name: "Fabio Cannavaro", realName: "Fabio Cannavaro", sport: "football",
    league: "SERIEA", position: "DEF", team: "Juventus", nation: "Italy", active: false, debutYear: 1992,
    blurb: "The last defender to win the Ballon d'Or, captaining Italy to the 2006 World Cup.",
    achievements: [
      ...T("ballon_dor", [2006]),
      ...T("fifa_best", [2006]),
      ...T("world_cup", [2006]),
      ...T("league_title", [2007, 2008], "Real Madrid"),
    ],
  },
  {
    id: "buffon", name: "Gianluigi Buffon", realName: "Gianluigi Buffon", sport: "football",
    league: "SERIEA", position: "GK", team: "Juventus", nation: "Italy", active: false, debutYear: 1995,
    blurb: "World Cup winner and the benchmark goalkeeper for two decades; three Champions League final losses.",
    achievements: [
      ...T("world_cup", [2006]),
      ...T("ballon_dor_2nd", [2006]),
      ...T("league_title", [2002, 2003, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020], "Juventus"),
      ...T("ucl_runnerup", [2003, 2015, 2017]),
      ...T("continental_nt_runnerup", [2012]),
    ],
  },
  {
    id: "mbappe", name: "Kylian Mbappé", realName: "Kylian Mbappé Lottin", sport: "football",
    league: "LIGUE1", position: "FWD", team: "Paris Saint-Germain", nation: "France", active: true, debutYear: 2015,
    blurb: "World Cup winner at 19 and a hat-trick in a final — the face of the post-Messi/Ronaldo era.",
    achievements: [
      ...T("world_cup", [2018]),
      ...T("wc_runnerup", [2022]),
      ...T("wc_golden_boot", [2022]),
      ...T("nations_league", [2021]),
      ...T("league_title", [2017], "Monaco"),
      ...T("league_title", [2018, 2019, 2020, 2022, 2023, 2024], "Paris Saint-Germain"),
      ...T("ballon_dor_2nd", [2023]),
    ],
  },
  {
    id: "henry", name: "Thierry Henry", realName: "Thierry Daniel Henry", sport: "football",
    league: "PL", position: "FWD", team: "Arsenal", nation: "France", active: false, debutYear: 1994,
    blurb: "Arsenal's greatest forward and an 'Invincible'; World Cup and Euro winner with France.",
    achievements: [
      ...T("world_cup", [1998]),
      ...T("continental_nt", [2000]),
      ...T("confederations_cup", [2003]),
      ...T("golden_shoe", [2004, 2005]),
      ...T("league_top_scorer", [2002, 2004, 2005, 2006], "Arsenal"),
      ...T("champions_league", [2009], "Barcelona"),
      ...T("league_title", [2002, 2004], "Arsenal"),
      ...T("league_title", [2009, 2010], "Barcelona"),
      ...T("ucl_runnerup", [2006]),
      ...T("club_world_cup", [2009], "Barcelona"),
    ],
  },

  // —— Batch 1: all-time greats (honors verified vs. Wikipedia, through 2024-25) ——
  {
    id: "eusebio", name: "Eusébio", realName: "Eusébio da Silva Ferreira", sport: "football",
    league: "PRIMEIRA", position: "FWD", team: "Benfica", nation: "Portugal", active: false, debutYear: 1961,
    i18n: { zh: "尤西比奥" },
    blurb: "Benfica's Black Panther — the 1965 Ballon d'Or and the 1966 World Cup Golden Boot.",
    achievements: [
      ...T("ballon_dor", [1965]),
      ...T("ballon_dor_2nd", [1962, 1966]),
      ...T("wc_golden_boot", [1966]),
      ...T("golden_shoe", [1968, 1973]),
      ...T("champions_league", [1962], "Benfica"),
      ...T("ucl_runnerup", [1963, 1965, 1968]),
      ...T("league_title", [1961, 1963, 1964, 1965, 1967, 1968, 1969, 1971, 1972, 1973, 1975], "Benfica"),
      ...T("domestic_cup", [1962, 1964, 1969, 1970, 1972], "Benfica"),
    ],
  },
  {
    id: "gerd-muller", name: "Gerd Müller", realName: "Gerhard Müller", sport: "football",
    league: "BUNDESLIGA", position: "FWD", team: "Bayern Munich", nation: "Germany", active: false, debutYear: 1963,
    i18n: { zh: "盖德·穆勒" },
    blurb: "Der Bomber — a then-record World Cup goal haul and three straight European Cups with Bayern.",
    achievements: [
      ...T("ballon_dor", [1970]),
      ...T("ballon_dor_2nd", [1972]),
      ...T("ballon_dor_3rd", [1969, 1973]),
      ...T("world_cup", [1974]),
      ...T("wc_golden_boot", [1970]),
      ...T("continental_nt", [1972]),
      ...T("golden_shoe", [1970, 1972]),
      ...T("league_top_scorer", [1967, 1969, 1970, 1972, 1973, 1974, 1978], "Bayern Munich"),
      ...T("champions_league", [1974, 1975, 1976], "Bayern Munich"),
      ...T("club_world_cup", [1976], "Bayern Munich"),
      ...T("league_title", [1969, 1972, 1973, 1974], "Bayern Munich"),
      ...T("domestic_cup", [1966, 1967, 1969, 1971], "Bayern Munich"),
    ],
  },
  {
    id: "puskas", name: "Ferenc Puskás", realName: "Ferenc Puskás", sport: "football",
    league: "LALIGA", position: "FWD", team: "Real Madrid", nation: "Hungary", active: false, debutYear: 1943,
    i18n: { zh: "普斯卡什" },
    blurb: "The Galloping Major — Olympic gold, a World Cup final, and three European Cups at Real Madrid.",
    achievements: [
      ...T("ballon_dor_2nd", [1960]),
      ...T("wc_runnerup", [1954]),
      ...T("wc_golden_ball", [1954]),
      ...T("olympic_gold_amateur", [1952]),
      ...T("league_top_scorer", [1960, 1961, 1963, 1964], "Real Madrid"),
      ...T("champions_league", [1959, 1960, 1966], "Real Madrid"),
      ...T("club_world_cup", [1960], "Real Madrid"),
      ...T("league_title", [1950, 1952, 1954, 1955], "Budapest Honvéd"),
      ...T("league_title", [1961, 1962, 1963, 1964, 1965], "Real Madrid"),
      ...T("domestic_cup", [1962], "Real Madrid"),
    ],
  },
  {
    id: "george-best", name: "George Best", realName: "George Best", sport: "football",
    league: "PL", position: "FWD", team: "Manchester United", nation: "Northern Ireland", active: false, debutYear: 1963,
    i18n: { zh: "乔治·贝斯特" },
    blurb: "Manchester United's mercurial genius — the 1968 Ballon d'Or and European Cup.",
    achievements: [
      ...T("ballon_dor", [1968]),
      ...T("ballon_dor_3rd", [1971]),
      ...T("league_top_scorer", [1968], "Manchester United"),
      ...T("champions_league", [1968], "Manchester United"),
      ...T("league_title", [1965, 1967], "Manchester United"),
    ],
  },
  {
    id: "romario", name: "Romário", realName: "Romário de Souza Faria", sport: "football",
    league: "SOUTHAM", position: "FWD", team: "Vasco da Gama", nation: "Brazil", active: false, debutYear: 1985,
    i18n: { zh: "罗马里奥" },
    blurb: "A penalty-box predator — the 1994 World Cup and FIFA World Player of the Year.",
    achievements: [
      ...T("fifa_best", [1994]),
      ...T("world_cup", [1994]),
      ...T("wc_golden_ball", [1994]),
      ...T("continental_nt", [1989, 1997]),
      ...T("confederations_cup", [1997]),
      ...T("league_top_scorer", [1994, 2000, 2001, 2005]),
      ...T("ucl_runnerup", [1994]),
      ...T("league_title", [1989, 1991, 1992], "PSV Eindhoven"),
      ...T("league_title", [1994], "Barcelona"),
      ...T("league_title", [2000], "Vasco da Gama"),
      ...T("domestic_cup", [1989, 1990], "PSV Eindhoven"),
    ],
  },
  {
    id: "rivaldo", name: "Rivaldo", realName: "Rivaldo Vítor Borba Ferreira", sport: "football",
    league: "LALIGA", position: "FWD", team: "Barcelona", nation: "Brazil", active: false, debutYear: 1991,
    i18n: { zh: "里瓦尔多" },
    blurb: "The 1999 Ballon d'Or and a 2002 World Cup winner in Brazil's celebrated front line.",
    achievements: [
      ...T("ballon_dor", [1999]),
      ...T("fifa_best", [1999]),
      ...T("world_cup", [2002]),
      ...T("wc_runnerup", [1998]),
      ...T("continental_nt", [1999]),
      ...T("confederations_cup", [1997]),
      ...T("champions_league", [2003], "AC Milan"),
      ...T("league_title", [1994], "Palmeiras"),
      ...T("league_title", [1998, 1999], "Barcelona"),
      ...T("domestic_cup", [1998], "Barcelona"),
    ],
  },
  {
    id: "roberto-baggio", name: "Roberto Baggio", realName: "Roberto Baggio", sport: "football",
    league: "SERIEA", position: "FWD", team: "Juventus", nation: "Italy", active: false, debutYear: 1982,
    i18n: { zh: "罗伯托·巴乔" },
    blurb: "Il Divin Codino — the 1993 Ballon d'Or; carried Italy to the 1994 World Cup final.",
    achievements: [
      ...T("ballon_dor", [1993]),
      ...T("ballon_dor_2nd", [1994]),
      ...T("fifa_best", [1993]),
      ...T("wc_runnerup", [1994]),
      ...T("europa_league", [1993], "Juventus"),
      ...T("league_title", [1995], "Juventus"),
      ...T("league_title", [1996], "AC Milan"),
      ...T("domestic_cup", [1995], "Juventus"),
    ],
  },
  {
    id: "batistuta", name: "Gabriel Batistuta", realName: "Gabriel Omar Batistuta", sport: "football",
    league: "SERIEA", position: "FWD", team: "Fiorentina", nation: "Argentina", active: false, debutYear: 1988,
    i18n: { zh: "巴蒂斯图塔" },
    blurb: "Batigol — Argentina's record scorer for a generation and Roma's 2001 Scudetto spearhead.",
    achievements: [
      ...T("continental_nt", [1991, 1993]),
      ...T("confederations_cup", [1992]),
      ...T("league_top_scorer", [1995], "Fiorentina"),
      ...T("league_title", [1990], "River Plate"),
      ...T("league_title", [1991], "Boca Juniors"),
      ...T("league_title", [2001], "Roma"),
      ...T("domestic_cup", [1996], "Fiorentina"),
    ],
  },
  {
    id: "shevchenko", name: "Andriy Shevchenko", realName: "Andriy Mykolayovych Shevchenko", sport: "football",
    league: "SERIEA", position: "FWD", team: "AC Milan", nation: "Ukraine", active: false, debutYear: 1994,
    i18n: { zh: "舍甫琴科" },
    blurb: "The 2004 Ballon d'Or and Milan's Champions League match-winner in 2003.",
    achievements: [
      ...T("ballon_dor", [2004]),
      ...T("league_top_scorer", [2000, 2004], "AC Milan"),
      ...T("champions_league", [2003], "AC Milan"),
      ...T("ucl_runnerup", [2005], "AC Milan"),
      ...T("ucl_runnerup", [2008], "Chelsea"),
      ...T("league_title", [1995, 1996, 1997, 1998, 1999], "Dynamo Kyiv"),
      ...T("league_title", [2004], "AC Milan"),
      ...T("domestic_cup", [1996, 1998, 1999], "Dynamo Kyiv"),
      ...T("domestic_cup", [2007], "Chelsea"),
    ],
  },
  {
    id: "garrincha", name: "Garrincha", realName: "Manuel Francisco dos Santos", sport: "football",
    league: "SOUTHAM", position: "FWD", team: "Botafogo", nation: "Brazil", active: false, debutYear: 1953,
    i18n: { zh: "加林查" },
    blurb: "Brazil's joyful winger — two World Cups and the best player of the 1962 tournament.",
    achievements: [
      ...T("world_cup", [1958, 1962]),
      ...T("wc_golden_ball", [1962]),
      ...T("wc_golden_boot", [1962]),
      ...T("ballon_dor_retro", [1962]),
    ],
  },
  {
    id: "baresi", name: "Franco Baresi", realName: "Franchino Baresi", sport: "football",
    league: "SERIEA", position: "DEF", team: "AC Milan", nation: "Italy", active: false, debutYear: 1977,
    i18n: { zh: "弗兰科·巴雷西" },
    blurb: "Milan's sweeper and captain — three European Cups and six Scudetti.",
    achievements: [
      ...T("world_cup", [1982]),
      ...T("wc_runnerup", [1994]),
      ...T("ballon_dor_2nd", [1989]),
      ...T("champions_league", [1989, 1990, 1994], "AC Milan"),
      ...T("club_world_cup", [1989, 1990], "AC Milan"),
      ...T("league_title", [1979, 1988, 1992, 1993, 1994, 1996], "AC Milan"),
    ],
  },
  {
    id: "bobby-moore", name: "Bobby Moore", realName: "Robert Frederick Chelsea Moore", sport: "football",
    league: "PL", position: "DEF", team: "West Ham United", nation: "England", active: false, debutYear: 1958,
    i18n: { zh: "博比·摩尔" },
    blurb: "England's World Cup-winning captain in 1966 — the defender's defender.",
    achievements: [
      ...T("world_cup", [1966]),
      ...T("ballon_dor_2nd", [1970]),
      ...T("domestic_cup", [1964], "West Ham United"),
    ],
  },
  {
    id: "cafu", name: "Cafu", realName: "Marcos Evangelista de Morais", sport: "football",
    league: "SERIEA", position: "DEF", team: "AS Roma", nation: "Brazil", active: false, debutYear: 1989,
    i18n: { zh: "卡富" },
    blurb: "Two-time World Cup winner and the most decorated right-back of his era.",
    achievements: [
      ...T("world_cup", [1994, 2002]),
      ...T("wc_runnerup", [1998]),
      ...T("continental_nt", [1997, 1999]),
      ...T("confederations_cup", [1997]),
      ...T("champions_league", [2007], "AC Milan"),
      ...T("copa_libertadores", [1992, 1993], "São Paulo"),
      ...T("club_world_cup", [1992, 1993], "São Paulo"),
      ...T("club_world_cup", [2007], "AC Milan"),
      ...T("league_title", [1991], "São Paulo"),
      ...T("league_title", [2001], "AS Roma"),
      ...T("league_title", [2004], "AC Milan"),
    ],
  },
  {
    id: "roberto-carlos", name: "Roberto Carlos", realName: "Roberto Carlos da Silva Rocha", sport: "football",
    league: "LALIGA", position: "DEF", team: "Real Madrid", nation: "Brazil", active: false, debutYear: 1992,
    i18n: { zh: "罗伯托·卡洛斯" },
    blurb: "Real Madrid's marauding left-back — three Champions Leagues and a 2002 World Cup.",
    achievements: [
      ...T("world_cup", [2002]),
      ...T("wc_runnerup", [1998]),
      ...T("continental_nt", [1997, 1999]),
      ...T("confederations_cup", [1997]),
      ...T("ballon_dor_2nd", [2002]),
      ...T("champions_league", [1998, 2000, 2002], "Real Madrid"),
      ...T("club_world_cup", [1998, 2002], "Real Madrid"),
      ...T("league_title", [1997, 2001, 2003, 2007], "Real Madrid"),
    ],
  },
  {
    id: "pirlo", name: "Andrea Pirlo", realName: "Andrea Pirlo", sport: "football",
    league: "SERIEA", position: "MID", team: "AC Milan", nation: "Italy", active: false, debutYear: 1995,
    i18n: { zh: "安德烈亚·皮尔洛" },
    blurb: "The deep-lying playmaker who won the 2006 World Cup and two Champions Leagues with Milan.",
    achievements: [
      ...T("world_cup", [2006]),
      ...T("continental_nt_runnerup", [2012]),
      ...T("champions_league", [2003, 2007], "AC Milan"),
      ...T("ucl_runnerup", [2005], "AC Milan"),
      ...T("club_world_cup", [2007], "AC Milan"),
      ...T("league_title", [2004, 2011], "AC Milan"),
      ...T("league_title", [2012, 2013, 2014, 2015], "Juventus"),
      ...T("domestic_cup", [2003], "AC Milan"),
      ...T("domestic_cup", [2015], "Juventus"),
    ],
  },
  {
    id: "gerrard", name: "Steven Gerrard", realName: "Steven George Gerrard", sport: "football",
    league: "PL", position: "MID", team: "Liverpool", nation: "England", active: false, debutYear: 1998,
    i18n: { zh: "史蒂文·杰拉德" },
    blurb: "Liverpool's talismanic captain and the driving force of the 2005 Istanbul comeback.",
    achievements: [
      ...T("champions_league", [2005], "Liverpool"),
      ...T("ucl_runnerup", [2007], "Liverpool"),
      ...T("europa_league", [2001], "Liverpool"),
      ...T("domestic_cup", [2001, 2006], "Liverpool"),
    ],
  },
  {
    id: "matthaus", name: "Lothar Matthäus", realName: "Lothar Herbert Matthäus", sport: "football",
    league: "BUNDESLIGA", position: "MID", team: "Bayern Munich", nation: "Germany", active: false, debutYear: 1979,
    i18n: { zh: "洛塔尔·马特乌斯" },
    blurb: "The 1990 World Cup-winning captain and the first FIFA World Player of the Year.",
    achievements: [
      ...T("ballon_dor", [1990]),
      ...T("fifa_best", [1991]),
      ...T("world_cup", [1990]),
      ...T("wc_runnerup", [1982, 1986]),
      ...T("continental_nt", [1980]),
      ...T("ucl_runnerup", [1987, 1999], "Bayern Munich"),
      ...T("europa_league", [1991], "Inter Milan"),
      ...T("europa_league", [1996], "Bayern Munich"),
      ...T("league_title", [1985, 1986, 1987, 1994, 1997, 1999], "Bayern Munich"),
      ...T("league_title", [1989], "Inter Milan"),
      ...T("domestic_cup", [1986, 1998], "Bayern Munich"),
    ],
  },
  {
    id: "zico", name: "Zico", realName: "Arthur Antunes Coimbra", sport: "football",
    league: "SOUTHAM", position: "MID", team: "Flamengo", nation: "Brazil", active: false, debutYear: 1971,
    i18n: { zh: "济科" },
    blurb: "The 'White Pelé' — Flamengo's 1981 Libertadores and Intercontinental Cup talisman.",
    achievements: [
      ...T("copa_libertadores", [1981], "Flamengo"),
      ...T("club_world_cup", [1981], "Flamengo"),
      ...T("league_title", [1980, 1982, 1983], "Flamengo"),
    ],
  },
  {
    id: "zoff", name: "Dino Zoff", realName: "Dino Zoff", sport: "football",
    league: "SERIEA", position: "GK", team: "Juventus", nation: "Italy", active: false, debutYear: 1961,
    i18n: { zh: "迪诺·佐夫" },
    blurb: "World Cup winner at 40 and Euro 1968 champion — Juventus's six-time Serie A keeper.",
    achievements: [
      ...T("world_cup", [1982]),
      ...T("continental_nt", [1968]),
      ...T("ballon_dor_2nd", [1973]),
      ...T("ucl_runnerup", [1973, 1983], "Juventus"),
      ...T("europa_league", [1977], "Juventus"),
      ...T("league_title", [1973, 1975, 1977, 1978, 1981, 1982], "Juventus"),
      ...T("domestic_cup", [1979, 1983], "Juventus"),
    ],
  },
  {
    id: "gullit", name: "Ruud Gullit", realName: "Ruud Gullit", sport: "football",
    league: "SERIEA", position: "MID", team: "AC Milan", nation: "Netherlands", active: false, debutYear: 1979,
    i18n: { zh: "路德·古利特" },
    blurb: "Euro 1988 captain and 1987 Ballon d'Or — the dreadlocked heart of Milan's great side.",
    achievements: [
      ...T("ballon_dor", [1987]),
      ...T("continental_nt", [1988]),
      ...T("champions_league", [1989, 1990], "AC Milan"),
      ...T("club_world_cup", [1990], "AC Milan"),
      ...T("league_title", [1984], "Feyenoord"),
      ...T("league_title", [1986, 1987], "PSV Eindhoven"),
      ...T("league_title", [1988, 1992, 1993], "AC Milan"),
      ...T("domestic_cup", [1984], "Feyenoord"),
      ...T("domestic_cup", [1994], "Sampdoria"),
      ...T("domestic_cup", [1997], "Chelsea"),
    ],
  },

  // —— Jiangsu City League (苏超) · 2025 inaugural-season award winners ——
  {
    id: "fan-houtai", name: "Fan Houtai", realName: "范厚泰", sport: "football",
    league: "JSL", position: "DEF", team: "Taizhou", nation: "China", active: true, debutYear: 2025,
    blurb: "A 20-year-old centre-back named Best Player of the inaugural 苏超 as Taizhou won the 2025 title on penalties.",
    achievements: [
      ...T("jsl_title", [2025], "Taizhou"),
      ...T("jsl_best_player", [2025]),
    ],
  },
  {
    id: "zhao-dongxu", name: "Zhao Dongxu", realName: "赵冬旭", sport: "football",
    league: "JSL", position: "GK", team: "Nantong", nation: "China", active: true, debutYear: 2025,
    blurb: "Best Goalkeeper of the 2025 苏超; Nantong reached the final before losing on penalties.",
    achievements: [
      ...T("jsl_best_gk", [2025]),
      ...T("jsl_runnerup", [2025], "Nantong"),
    ],
  },
  {
    id: "teng-shuai", name: "Teng Shuai", realName: "滕帅", sport: "football",
    league: "JSL", position: "FWD", team: "Nanjing", nation: "China", active: true, debutYear: 2025,
    blurb: "Former CSL Jiangsu player; shared the 2025 苏超 Golden Boot with nine goals for Nanjing.",
    achievements: [
      ...T("jsl_golden_boot", [2025]),
    ],
  },
  {
    id: "gao-chi", name: "Gao Chi", realName: "高驰", sport: "football",
    league: "JSL", position: "FWD", team: "Suqian", nation: "China", active: true, debutYear: 2025,
    blurb: "A university student who shared the 2025 苏超 Golden Boot with nine goals for Suqian.",
    achievements: [
      ...T("jsl_golden_boot", [2025]),
    ],
  },

  // —— Managers (kind: "coach") · ranked by honors won as a head coach ——
  {
    id: "guardiola", name: "Pep Guardiola", realName: "Josep Guardiola i Sala", sport: "football",
    league: "PL", position: "Manager", team: "Manchester City", nation: "Spain", active: true, debutYear: 2007,
    kind: "coach", i18n: { zh: "何塞普·瓜迪奥拉" },
    blurb: "The defining tactician of the era — treble-winning sides at Barcelona and Manchester City.",
    achievements: [
      ...T("champions_league", [2009, 2011], "Barcelona"),
      ...T("champions_league", [2023], "Manchester City"),
      ...T("league_title", [2009, 2010, 2011], "Barcelona"),
      ...T("league_title", [2014, 2015, 2016], "Bayern Munich"),
      ...T("league_title", [2018, 2019, 2021, 2022, 2023, 2024], "Manchester City"),
      ...T("club_world_cup", [2009, 2011], "Barcelona"),
      ...T("club_world_cup", [2023], "Manchester City"),
      ...T("best_coach", [2011, 2023]),
    ],
  },
  {
    id: "ancelotti", name: "Carlo Ancelotti", realName: "Carlo Ancelotti", sport: "football",
    league: "LALIGA", position: "Manager", team: "Real Madrid", nation: "Italy", active: true, debutYear: 1995,
    kind: "coach", i18n: { zh: "卡洛·安切洛蒂" },
    blurb: "Record five-time Champions League-winning manager, with a league title in each of Europe's top five.",
    achievements: [
      ...T("champions_league", [2003, 2007], "AC Milan"),
      ...T("champions_league", [2014, 2022, 2024], "Real Madrid"),
      ...T("league_title", [2004], "AC Milan"),
      ...T("league_title", [2010], "Chelsea"),
      ...T("league_title", [2013], "Paris Saint-Germain"),
      ...T("league_title", [2017], "Bayern Munich"),
      ...T("league_title", [2022, 2024], "Real Madrid"),
      ...T("club_world_cup", [2007], "AC Milan"),
      ...T("club_world_cup", [2014, 2022], "Real Madrid"),
      ...T("best_coach", [2024]),
    ],
  },
  {
    id: "ferguson", name: "Alex Ferguson", realName: "Sir Alexander Chapman Ferguson", sport: "football",
    league: "PL", position: "Manager", team: "Manchester United", nation: "Scotland", active: false, debutYear: 1974,
    kind: "coach", i18n: { zh: "亚历克斯·弗格森" },
    blurb: "Built two decades of dynasties at Manchester United — two Champions Leagues, thirteen league titles.",
    achievements: [
      ...T("champions_league", [1999, 2008], "Manchester United"),
      ...T("league_title", [1993, 1994, 1996, 1997, 1999, 2000, 2001, 2003, 2007, 2008, 2009, 2011, 2013], "Manchester United"),
      ...T("club_world_cup", [2008], "Manchester United"),
      ...T("best_coach", [1999, 2008]),
    ],
  },
  {
    id: "mourinho", name: "José Mourinho", realName: "José Mário dos Santos Mourinho Félix", sport: "football",
    league: "PL", position: "Manager", team: "Chelsea", nation: "Portugal", active: true, debutYear: 2000,
    kind: "coach", i18n: { zh: "若泽·穆里尼奥" },
    blurb: "The Special One — Champions Leagues with Porto and Inter, and league titles in four countries.",
    achievements: [
      ...T("champions_league", [2004], "Porto"),
      ...T("champions_league", [2010], "Inter Milan"),
      ...T("europa_league", [2003], "Porto"),
      ...T("europa_league", [2017], "Manchester United"),
      ...T("league_title", [2003, 2004], "Porto"),
      ...T("league_title", [2005, 2006, 2015], "Chelsea"),
      ...T("league_title", [2009, 2010], "Inter Milan"),
      ...T("league_title", [2012], "Real Madrid"),
      ...T("club_world_cup", [2010], "Inter Milan"),
      ...T("best_coach", [2010]),
    ],
  },
  {
    id: "zidane-coach", name: "Zinedine Zidane", realName: "Zinédine Yazid Zidane", sport: "football",
    league: "LALIGA", position: "Manager", team: "Real Madrid", nation: "France", active: false, debutYear: 2016,
    kind: "coach", alsoId: "zidane", i18n: { zh: "齐内丁·齐达内" },
    blurb: "Won the Champions League three seasons running as Real Madrid's manager — after starring as a player.",
    achievements: [
      ...T("champions_league", [2016, 2017, 2018], "Real Madrid"),
      ...T("league_title", [2017, 2020], "Real Madrid"),
      ...T("club_world_cup", [2016, 2017, 2018], "Real Madrid"),
      ...T("best_coach", [2017]),
    ],
  },
  {
    id: "beckenbauer-coach", name: "Franz Beckenbauer", realName: "Franz Anton Beckenbauer", sport: "football",
    league: "BUNDESLIGA", position: "Manager", team: "Bayern Munich", nation: "Germany", active: false, debutYear: 1984,
    kind: "coach", alsoId: "beckenbauer", i18n: { zh: "弗朗茨·贝肯鲍尔" },
    blurb: "Lifted the 1990 World Cup as manager — having won it as captain in 1974.",
    achievements: [
      ...T("world_cup", [1990]),
      ...T("league_title", [1994], "Bayern Munich"),
      ...T("europa_league", [1996], "Bayern Munich"),
    ],
  },
  {
    id: "cruyff-coach", name: "Johan Cruyff", realName: "Hendrik Johannes Cruijff", sport: "football",
    league: "LALIGA", position: "Manager", team: "Barcelona", nation: "Netherlands", active: false, debutYear: 1985,
    kind: "coach", alsoId: "cruyff", i18n: { zh: "约翰·克鲁伊夫" },
    blurb: "Built Barcelona's 'Dream Team' and its first European Cup — the cradle of modern positional play.",
    achievements: [
      ...T("champions_league", [1992], "Barcelona"),
      ...T("league_title", [1991, 1992, 1993, 1994], "Barcelona"),
    ],
  },
  {
    id: "klopp", name: "Jürgen Klopp", realName: "Jürgen Norbert Klopp", sport: "football",
    league: "PL", position: "Manager", team: "Liverpool", nation: "Germany", active: true, debutYear: 2001,
    kind: "coach", i18n: { zh: "尤尔根·克洛普" },
    blurb: "Heavy-metal football — a Champions League and Liverpool's first league title in 30 years.",
    achievements: [
      ...T("champions_league", [2019], "Liverpool"),
      ...T("league_title", [2011, 2012], "Borussia Dortmund"),
      ...T("league_title", [2020], "Liverpool"),
      ...T("club_world_cup", [2019], "Liverpool"),
      ...T("best_coach", [2019, 2020]),
    ],
  },
  {
    id: "lippi", name: "Marcello Lippi", realName: "Marcello Lippi", sport: "football",
    league: "SERIEA", position: "Manager", team: "Juventus", nation: "Italy", active: false, debutYear: 1989,
    kind: "coach", i18n: { zh: "马尔切洛·里皮" },
    blurb: "World Cup winner with Italy in 2006, and a Champions League with Juventus.",
    achievements: [
      ...T("world_cup", [2006]),
      ...T("champions_league", [1996], "Juventus"),
      ...T("league_title", [1995, 1997, 1998, 2002, 2003], "Juventus"),
      ...T("club_world_cup", [1996], "Juventus"),
    ],
  },
  {
    id: "del-bosque", name: "Vicente del Bosque", realName: "Vicente del Bosque González", sport: "football",
    league: "LALIGA", position: "Manager", team: "Real Madrid", nation: "Spain", active: false, debutYear: 1999,
    kind: "coach", i18n: { zh: "比森特·德尔·博斯克" },
    blurb: "Won the Champions League, the World Cup and the European Championship as a head coach.",
    achievements: [
      ...T("world_cup", [2010]),
      ...T("continental_nt", [2012]),
      ...T("champions_league", [2000, 2002], "Real Madrid"),
      ...T("league_title", [2001, 2003], "Real Madrid"),
      ...T("club_world_cup", [2002], "Real Madrid"),
    ],
  },
  {
    id: "sacchi", name: "Arrigo Sacchi", realName: "Arrigo Sacchi", sport: "football",
    league: "SERIEA", position: "Manager", team: "AC Milan", nation: "Italy", active: false, debutYear: 1985,
    kind: "coach", i18n: { zh: "阿里戈·萨基" },
    blurb: "His pressing, zonal Milan of the late 1980s reshaped how the game is played.",
    achievements: [
      ...T("champions_league", [1989, 1990], "AC Milan"),
      ...T("league_title", [1988], "AC Milan"),
      ...T("club_world_cup", [1989, 1990], "AC Milan"),
    ],
  },
  {
    id: "deschamps", name: "Didier Deschamps", realName: "Didier Claude Deschamps", sport: "football",
    league: "LIGUE1", position: "Manager", team: "France", nation: "France", active: true, debutYear: 2001,
    kind: "coach", i18n: { zh: "迪迪埃·德尚" },
    blurb: "Lifted the World Cup as France's coach in 2018 — having captained the 1998 winners.",
    achievements: [
      ...T("world_cup", [2018]),
      ...T("wc_runnerup", [2022]),
      ...T("nations_league", [2021]),
      ...T("league_title", [2010], "Marseille"),
      ...T("best_coach", [2018]),
    ],
  },
];
