// Download the freely-licensed portraits found by the photo-extract workflow and
// (re)generate src/lib/player-photos.ts. Usage:
//   node scripts/fetch-photos.mjs <workflow-output.json>
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import sharp from "sharp";

const OUT = process.argv[2];
if (!OUT) {
  console.error("usage: node scripts/fetch-photos.mjs <workflow-output.json>");
  process.exit(1);
}
let raw = fs.readFileSync(OUT, "utf8").trim();
// Be tolerant of any leading/trailing noise around the JSON object.
const s = raw.indexOf("{");
const e = raw.lastIndexOf("}");
const parsed = JSON.parse(raw.slice(s, e + 1));
const data = parsed.result || parsed; // workflow output nests the return under `result`
const found = (data.found || []).filter((f) => f && f.found && f.imageUrl && f.id);

const PUB = path.join(process.cwd(), "public", "players");
fs.mkdirSync(PUB, { recursive: true });
const UA = "PantheonBot/1.0 (https://pantheon.ungetsu.net; yunyue.li@mirofish.ai)";

const ok = [];
for (const f of found) {
  const dest = path.join(PUB, `${f.id}.webp`);
  const tmp = path.join(PUB, `${f.id}.download`);
  try {
    // curl is reliable against Wikimedia (node fetch + constructed thumbs 400'd). Download the URL as-is.
    execFileSync("curl", ["-sL", "--fail", "--max-time", "40", "-A", UA, "-o", tmp, f.imageUrl], { stdio: "ignore" });
    const buf = fs.readFileSync(tmp);
    const isJpg = buf.subarray(0, 3).toString("hex") === "ffd8ff";
    const isPng = buf.subarray(0, 8).toString("hex") === "89504e470d0a1a0a";
    if (buf.length < 3000 || !(isJpg || isPng)) {
      fs.rmSync(tmp, { force: true });
      console.log("SKIP non-image/small", f.id, buf.length);
      continue;
    }
    // Convert to a resized WebP (max 800px long edge, q80) — matches optimize-photos.mjs.
    await sharp(tmp)
      .resize(800, 800, { fit: "inside", withoutEnlargement: true })
      .webp({ quality: 80 })
      .toFile(dest);
    fs.rmSync(tmp, { force: true });
    ok.push(f);
    console.log("OK", f.id, `${(fs.statSync(dest).size / 1024) | 0}KB`);
  } catch (err) {
    fs.rmSync(tmp, { force: true });
    fs.rmSync(dest, { force: true });
    console.log("FAIL", f.id, String(err.message || err).slice(0, 50));
  }
}

const esc = (v) => String(v ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\s+/g, " ").trim();
const rows = ok
  .sort((a, b) => a.id.localeCompare(b.id))
  .map(
    (f) =>
      `  ${JSON.stringify(f.id)}: { src: "/players/${f.id}.webp", author: "${esc(f.author)}", license: "${esc(f.license)}", licenseUrl: "${esc(f.licenseUrl)}", source: "${esc(f.sourcePage)}" },`
  )
  .join("\n");

const file = `// Freely-licensed player portraits. GENERATED by scripts/fetch-photos.mjs from the
// photo-extraction workflow — do not hand-edit; re-run the workflow + script to refresh.
// Every entry is surfaced on /credits for attribution (mostly CC BY / CC BY-SA from
// Wikimedia Commons). Players without a free image fall back to the radiant field.
export type PhotoCredit = {
  /** Public path, e.g. "/players/messi.webp". */
  src: string;
  /** Photographer / author, as named on Commons. */
  author: string;
  /** Human label, e.g. "CC BY-SA 4.0" or "Public domain". */
  license: string;
  /** Canonical license deed URL (empty for public domain). */
  licenseUrl: string;
  /** Wikimedia Commons file page. */
  source: string;
};

export const PLAYER_PHOTOS: Record<string, PhotoCredit> = {
${rows}
};

export function playerPhoto(id: string): PhotoCredit | undefined {
  return PLAYER_PHOTOS[id];
}
`;

fs.writeFileSync(path.join(process.cwd(), "src", "lib", "player-photos.ts"), file);
console.log(`\nmanifest: ${ok.length} photos written to src/lib/player-photos.ts (of ${found.length} found)`);
